CREATE TABLE document_source_revisions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_document_id BIGINT       NOT NULL
        REFERENCES product_documents (id) ON DELETE CASCADE,
    revision_number     INTEGER      NOT NULL,
    file_name           VARCHAR(255) NOT NULL,
    media_type          VARCHAR(150) NOT NULL,
    file_size           BIGINT       NOT NULL,
    checksum            VARCHAR(64)  NOT NULL,
    storage_key         VARCHAR(500) NOT NULL,
    source_hash         VARCHAR(64)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_document_source_revisions_revision
        CHECK (revision_number > 0),
    CONSTRAINT ck_document_source_revisions_file_name
        CHECK (btrim(file_name) <> ''),
    CONSTRAINT ck_document_source_revisions_media_type
        CHECK (btrim(media_type) <> ''),
    CONSTRAINT ck_document_source_revisions_file_size
        CHECK (file_size >= 0),
    CONSTRAINT ck_document_source_revisions_checksum
        CHECK (checksum ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_source_revisions_storage_key
        CHECK (btrim(storage_key) <> ''),
    CONSTRAINT ck_document_source_revisions_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ux_document_source_revisions_document_revision
        UNIQUE (product_document_id, revision_number)
);

CREATE INDEX idx_document_source_revisions_source_hash
    ON document_source_revisions (source_hash);

COMMENT ON TABLE document_source_revisions IS
    'Append-only identity and file metadata for each persisted product document source.';
COMMENT ON COLUMN document_source_revisions.source_hash IS
    'Lowercase SHA-256 hex of the complete immutable source bytes.';

CREATE FUNCTION reject_document_source_revision_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
        OR EXISTS (
            SELECT 1
            FROM product_documents
            WHERE id = OLD.product_document_id
        )
    THEN
        RAISE EXCEPTION 'document_source_revisions records are immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN OLD;
END;
$$;

CREATE TRIGGER trg_document_source_revisions_immutable
BEFORE UPDATE OR DELETE ON document_source_revisions
FOR EACH ROW
EXECUTE FUNCTION reject_document_source_revision_changes();
