CREATE TABLE analysis_executions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT       NOT NULL REFERENCES analyses (id),
    attempt_no          INTEGER      NOT NULL,
    execution_token     VARCHAR(36)  NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    error_code          VARCHAR(60),
    retryable           BOOLEAN      NOT NULL DEFAULT FALSE,
    retrieval_version   VARCHAR(100) NOT NULL,
    provider_risk_score INTEGER,
    model_version       VARCHAR(50),
    prompt_version      VARCHAR(50),
    started_at          TIMESTAMPTZ  NOT NULL,
    finished_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ux_analysis_executions_attempt UNIQUE (analysis_id, attempt_no),
    CONSTRAINT ux_analysis_executions_token UNIQUE (execution_token),
    CONSTRAINT ck_analysis_executions_attempt CHECK (attempt_no > 0),
    CONSTRAINT ck_analysis_executions_token CHECK (btrim(execution_token) <> ''),
    CONSTRAINT ck_analysis_executions_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'DISCARDED')),
    CONSTRAINT ck_analysis_executions_retrieval_version
        CHECK (btrim(retrieval_version) <> ''),
    CONSTRAINT ck_analysis_executions_finished_at
        CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT ck_analysis_executions_lifecycle CHECK (
        (status = 'RUNNING'
            AND finished_at IS NULL
            AND error_code IS NULL
            AND retryable = FALSE
            AND provider_risk_score IS NULL
            AND model_version IS NULL
            AND prompt_version IS NULL)
        OR
        (status = 'SUCCEEDED'
            AND finished_at IS NOT NULL
            AND error_code IS NULL
            AND retryable = FALSE
            AND provider_risk_score IS NOT NULL
            AND model_version IS NOT NULL
            AND btrim(model_version) <> ''
            AND prompt_version IS NOT NULL
            AND btrim(prompt_version) <> '')
        OR
        (status = 'FAILED'
            AND finished_at IS NOT NULL
            AND error_code IS NOT NULL
            AND btrim(error_code) <> ''
            AND provider_risk_score IS NULL
            AND model_version IS NULL
            AND prompt_version IS NULL)
        OR
        (status = 'DISCARDED'
            AND finished_at IS NOT NULL
            AND error_code IS NOT NULL
            AND btrim(error_code) <> ''
            AND retryable = FALSE
            AND provider_risk_score IS NULL
            AND model_version IS NULL
            AND prompt_version IS NULL)
    )
);

CREATE INDEX idx_analysis_executions_analysis
    ON analysis_executions (analysis_id, attempt_no DESC);

ALTER TABLE analyses
    ADD COLUMN current_successful_execution_id BIGINT
        REFERENCES analysis_executions (id);

ALTER TABLE analysis_rag_runs
    ADD COLUMN analysis_execution_id BIGINT
        REFERENCES analysis_executions (id),
    ALTER COLUMN analysis_id DROP NOT NULL,
    DROP CONSTRAINT ux_analysis_rag_runs_analysis,
    ADD CONSTRAINT ck_analysis_rag_runs_execution_boundary CHECK (
        (analysis_execution_id IS NOT NULL AND analysis_id IS NULL)
        OR (analysis_execution_id IS NULL AND analysis_id IS NOT NULL)
    );

CREATE INDEX idx_analysis_rag_runs_execution
    ON analysis_rag_runs (analysis_execution_id);

COMMENT ON TABLE analysis_executions IS
    'One durable execution attempt. A retry appends a new attempt instead of replacing evidence.';
COMMENT ON COLUMN analysis_executions.provider_risk_score IS
    'Opaque score returned by the provider; no score is derived at this boundary.';
COMMENT ON COLUMN analyses.current_successful_execution_id IS
    'Mutable projection pointer set only after a successful execution and all of its evidence are persisted.';
COMMENT ON COLUMN analysis_rag_runs.analysis_id IS
    'Legacy owner retained only for pre-execution-boundary rows; it is never used to infer an execution.';
COMMENT ON COLUMN analysis_rag_runs.analysis_execution_id IS
    'Immutable execution boundary for newly captured retrieval runs.';

CREATE FUNCTION reject_analysis_execution_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'analysis_executions records cannot be deleted'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.status <> 'RUNNING' THEN
        RAISE EXCEPTION 'terminal analysis_executions records are immutable'
            USING ERRCODE = '55000';
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
        OR NEW.analysis_id IS DISTINCT FROM OLD.analysis_id
        OR NEW.attempt_no IS DISTINCT FROM OLD.attempt_no
        OR NEW.execution_token IS DISTINCT FROM OLD.execution_token
        OR NEW.retrieval_version IS DISTINCT FROM OLD.retrieval_version
        OR NEW.started_at IS DISTINCT FROM OLD.started_at
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
        OR NEW.status = 'RUNNING'
    THEN
        RAISE EXCEPTION 'analysis_executions execution boundary is immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_analysis_executions_append_only
BEFORE UPDATE OR DELETE ON analysis_executions
FOR EACH ROW
EXECUTE FUNCTION reject_analysis_execution_changes();

-- V14 temporarily allowed a RUNNING analysis to replace its retrieval evidence.
-- From this boundary onward both legacy and execution-bound runs remain immutable.
CREATE OR REPLACE FUNCTION reject_analysis_rag_run_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'analysis_rag_runs records are immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION reject_analysis_rag_snapshot_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'analysis_rag_retrieval_snapshots records are immutable'
        USING ERRCODE = '55000';
END;
$$;
