ALTER TABLE analysis_executions
    ADD CONSTRAINT ux_analysis_executions_id_analysis
        UNIQUE (id, analysis_id);

ALTER TABLE findings
    ADD COLUMN analysis_execution_id BIGINT,
    ADD COLUMN lineage_id VARCHAR(36),
    ADD COLUMN revision_number INTEGER,
    ADD COLUMN supersedes_finding_id BIGINT,
    ADD CONSTRAINT fk_findings_execution_analysis
        FOREIGN KEY (analysis_execution_id, analysis_id)
        REFERENCES analysis_executions (id, analysis_id),
    ADD CONSTRAINT fk_findings_supersedes
        FOREIGN KEY (supersedes_finding_id)
        REFERENCES findings (id),
    ADD CONSTRAINT ck_findings_revision_identity CHECK (
        (analysis_execution_id IS NULL
            AND lineage_id IS NULL
            AND revision_number IS NULL
            AND supersedes_finding_id IS NULL)
        OR
        (analysis_execution_id IS NOT NULL
            AND lineage_id IS NOT NULL
            AND lineage_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            AND revision_number > 0
            AND ((revision_number = 1 AND supersedes_finding_id IS NULL)
                OR (revision_number > 1 AND supersedes_finding_id IS NOT NULL)))
    ),
    ADD CONSTRAINT ck_findings_not_self_superseding CHECK (
        supersedes_finding_id IS NULL OR supersedes_finding_id <> id
    );

CREATE UNIQUE INDEX ux_findings_lineage_revision
    ON findings (lineage_id, revision_number)
    WHERE lineage_id IS NOT NULL;

CREATE UNIQUE INDEX ux_findings_superseded_once
    ON findings (supersedes_finding_id)
    WHERE supersedes_finding_id IS NOT NULL;

CREATE INDEX idx_findings_execution
    ON findings (analysis_execution_id, id);

CREATE FUNCTION validate_finding_revision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    predecessor findings%ROWTYPE;
BEGIN
    IF NEW.analysis_execution_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.revision_number = 1 THEN
        RETURN NEW;
    END IF;

    SELECT * INTO predecessor
    FROM findings
    WHERE id = NEW.supersedes_finding_id;

    IF NOT FOUND
        OR predecessor.analysis_execution_id IS NULL
        OR predecessor.analysis_id <> NEW.analysis_id
        OR predecessor.lineage_id <> NEW.lineage_id
        OR predecessor.revision_number + 1 <> NEW.revision_number
    THEN
        RAISE EXCEPTION 'finding revision must immediately supersede the same execution-bound lineage'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_findings_validate_revision
BEFORE INSERT ON findings
FOR EACH ROW
EXECUTE FUNCTION validate_finding_revision();

CREATE FUNCTION reject_execution_bound_finding_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.analysis_execution_id IS NOT NULL THEN
        RAISE EXCEPTION 'execution-bound finding revisions are immutable'
            USING ERRCODE = '55000';
    END IF;

    IF TG_OP = 'UPDATE'
        AND (NEW.analysis_execution_id IS NOT NULL
            OR NEW.lineage_id IS NOT NULL
            OR NEW.revision_number IS NOT NULL
            OR NEW.supersedes_finding_id IS NOT NULL)
    THEN
        RAISE EXCEPTION 'legacy findings cannot be assigned a revision identity'
            USING ERRCODE = '55000';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        RETURN NEW;
    END IF;

    RETURN OLD;
END;
$$;

CREATE TRIGGER trg_findings_execution_bound_immutable
BEFORE UPDATE OR DELETE ON findings
FOR EACH ROW
EXECUTE FUNCTION reject_execution_bound_finding_changes();

ALTER TABLE document_source_revisions
    ADD CONSTRAINT ux_document_source_revisions_anchor_identity
        UNIQUE (id, product_document_id, source_hash);

ALTER TABLE evidence_document_chunks
    ADD CONSTRAINT ux_evidence_document_chunks_anchor_identity
        UNIQUE (id, evidence_document_id, source_hash);

CREATE TABLE finding_evidence_anchors (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id           BIGINT       NOT NULL REFERENCES findings (id),
    source_role          VARCHAR(30)  NOT NULL,
    source_document_id   BIGINT,
    source_revision_id   BIGINT,
    evidence_document_id BIGINT,
    retrieved_chunk_id   BIGINT,
    source_hash          VARCHAR(64)  NOT NULL,
    page_number          INTEGER      NOT NULL,
    utf8_start_offset    BIGINT       NOT NULL,
    utf8_end_offset      BIGINT       NOT NULL,
    excerpt_hash         VARCHAR(64)  NOT NULL,
    exact_excerpt        TEXT         NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_finding_evidence_anchors_document_source
        FOREIGN KEY (source_revision_id, source_document_id, source_hash)
        REFERENCES document_source_revisions (id, product_document_id, source_hash),
    CONSTRAINT fk_finding_evidence_anchors_policy_source
        FOREIGN KEY (retrieved_chunk_id, evidence_document_id, source_hash)
        REFERENCES evidence_document_chunks (id, evidence_document_id, source_hash),
    CONSTRAINT ck_finding_evidence_anchors_role
        CHECK (source_role IN ('DOCUMENT_CLAIM', 'POLICY_REQUIREMENT')),
    CONSTRAINT ck_finding_evidence_anchors_source_identity CHECK (
        (source_role = 'DOCUMENT_CLAIM'
            AND source_document_id IS NOT NULL
            AND source_revision_id IS NOT NULL
            AND evidence_document_id IS NULL
            AND retrieved_chunk_id IS NULL)
        OR
        (source_role = 'POLICY_REQUIREMENT'
            AND source_document_id IS NULL
            AND source_revision_id IS NULL
            AND evidence_document_id IS NOT NULL
            AND retrieved_chunk_id IS NOT NULL)
    ),
    CONSTRAINT ck_finding_evidence_anchors_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_finding_evidence_anchors_page
        CHECK (page_number > 0),
    CONSTRAINT ck_finding_evidence_anchors_utf8_range
        CHECK (utf8_start_offset >= 0 AND utf8_end_offset > utf8_start_offset),
    CONSTRAINT ck_finding_evidence_anchors_excerpt_hash
        CHECK (excerpt_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_finding_evidence_anchors_excerpt
        CHECK (octet_length(exact_excerpt) = utf8_end_offset - utf8_start_offset)
);

CREATE UNIQUE INDEX ux_finding_evidence_anchors_identity
    ON finding_evidence_anchors (
        finding_id,
        source_role,
        source_document_id,
        source_revision_id,
        evidence_document_id,
        retrieved_chunk_id,
        source_hash,
        page_number,
        utf8_start_offset,
        utf8_end_offset,
        excerpt_hash
    ) NULLS NOT DISTINCT;

CREATE INDEX idx_finding_evidence_anchors_finding
    ON finding_evidence_anchors (finding_id, id);

CREATE FUNCTION validate_finding_evidence_anchor()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM findings
        WHERE id = NEW.finding_id
          AND analysis_execution_id IS NOT NULL
          AND lineage_id IS NOT NULL
          AND revision_number IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'evidence anchors require an execution-bound finding revision'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_finding_evidence_anchors_validate
BEFORE INSERT ON finding_evidence_anchors
FOR EACH ROW
EXECUTE FUNCTION validate_finding_evidence_anchor();

CREATE FUNCTION reject_finding_evidence_anchor_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'finding_evidence_anchors records are immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_finding_evidence_anchors_immutable
BEFORE UPDATE OR DELETE ON finding_evidence_anchors
FOR EACH ROW
EXECUTE FUNCTION reject_finding_evidence_anchor_changes();

COMMENT ON COLUMN findings.analysis_execution_id IS
    'Execution boundary for new finding revisions; null only on legacy rows.';
COMMENT ON COLUMN findings.lineage_id IS
    'Stable UUID shared by all immutable revisions of one logical finding.';
COMMENT ON TABLE finding_evidence_anchors IS
    'Immutable exact UTF-8 source evidence for an execution-bound finding revision.';
COMMENT ON COLUMN finding_evidence_anchors.source_hash IS
    'Lowercase SHA-256 of the immutable document revision or indexed policy source.';
COMMENT ON COLUMN finding_evidence_anchors.excerpt_hash IS
    'Lowercase SHA-256 of exact_excerpt UTF-8 bytes.';
