ALTER TABLE reviews
    ADD COLUMN analysis_execution_id BIGINT;

UPDATE reviews r
SET analysis_execution_id = a.current_successful_execution_id
FROM analyses a
WHERE a.id = r.analysis_id
  AND a.current_successful_execution_id IS NOT NULL;

ALTER TABLE reviews
    ADD CONSTRAINT ux_reviews_id_execution
        UNIQUE (id, analysis_execution_id),
    ADD CONSTRAINT fk_reviews_execution_analysis
        FOREIGN KEY (analysis_execution_id, analysis_id)
        REFERENCES analysis_executions (id, analysis_id);

ALTER TABLE findings
    ADD CONSTRAINT ux_findings_id_execution
        UNIQUE (id, analysis_execution_id);

CREATE TABLE finding_review_decisions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id             BIGINT        NOT NULL,
    analysis_execution_id BIGINT        NOT NULL,
    finding_revision_id   BIGINT        NOT NULL,
    reviewer_id           BIGINT        NOT NULL REFERENCES users (id),
    decision              VARCHAR(20)   NOT NULL,
    comment               VARCHAR(1000),
    decided_at            TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ux_finding_review_decisions_review_finding
        UNIQUE (review_id, finding_revision_id),
    CONSTRAINT fk_finding_review_decisions_review_execution
        FOREIGN KEY (review_id, analysis_execution_id)
        REFERENCES reviews (id, analysis_execution_id),
    CONSTRAINT fk_finding_review_decisions_finding_execution
        FOREIGN KEY (finding_revision_id, analysis_execution_id)
        REFERENCES findings (id, analysis_execution_id),
    CONSTRAINT ck_finding_review_decisions_decision
        CHECK (decision IN ('APPROVED', 'REJECTED'))
);

CREATE INDEX idx_finding_review_decisions_review_decision
    ON finding_review_decisions (review_id, decision, finding_revision_id);

INSERT INTO finding_review_decisions (
    review_id,
    analysis_execution_id,
    finding_revision_id,
    reviewer_id,
    decision,
    comment,
    decided_at
)
SELECT r.id,
       r.analysis_execution_id,
       f.id,
       r.reviewer_id,
       CASE
           WHEN r.status = 'APPROVED'
               AND rsf.finding_id IS NOT NULL
               THEN 'APPROVED'
           ELSE 'REJECTED'
       END,
       r.comment,
       r.decided_at
FROM reviews r
JOIN findings f
  ON f.analysis_execution_id = r.analysis_execution_id
LEFT JOIN review_selected_findings rsf
  ON rsf.review_id = r.id
 AND rsf.finding_id = f.id
WHERE r.status IN ('APPROVED', 'REJECTED')
  AND r.analysis_execution_id IS NOT NULL
  AND r.reviewer_id IS NOT NULL
  AND r.decided_at IS NOT NULL;

CREATE FUNCTION validate_review_execution_boundary()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.analysis_execution_id IS NULL THEN
        RAISE EXCEPTION 'new reviews require an analysis execution boundary'
            USING ERRCODE = '23502';
    END IF;

    IF TG_OP = 'INSERT' AND NOT EXISTS (
        SELECT 1
        FROM analyses
        WHERE id = NEW.analysis_id
          AND current_successful_execution_id = NEW.analysis_execution_id
    ) THEN
        RAISE EXCEPTION 'a new review must bind the current successful execution'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'UPDATE'
        AND NEW.analysis_execution_id IS DISTINCT FROM OLD.analysis_execution_id
    THEN
        RAISE EXCEPTION 'a review execution boundary is immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_reviews_execution_boundary
BEFORE INSERT OR UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION validate_review_execution_boundary();

CREATE FUNCTION reject_finding_review_decision_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'finding_review_decisions records are append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_finding_review_decisions_append_only
BEFORE UPDATE OR DELETE ON finding_review_decisions
FOR EACH ROW
EXECUTE FUNCTION reject_finding_review_decision_changes();

COMMENT ON COLUMN reviews.analysis_execution_id IS
    'Immutable successful execution reviewed by this aggregate; null only on legacy rows.';
COMMENT ON TABLE finding_review_decisions IS
    'Append-only reviewer decisions for immutable execution-bound Finding revisions.';
