-- =============================================================================
-- GuardLab MVP 초기 스키마 (확정 ERD 17테이블)
-- 기준: GuardLab_MVP_데이터_명세서 v0.3 / erd/guardlab.dbml (2026-09-03)
--
-- 도메인 enum은 Postgres native ENUM 타입 대신 VARCHAR + CHECK 제약으로 만든다.
-- Hibernate @Enumerated(STRING)이 별도 타입 매핑 없이 동작하고,
-- 값 추가 시 마이그레이션이 단순해진다.
-- =============================================================================

-- ============================== 01. IDENTITY =================================

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    role       VARCHAR(30)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_users_role CHECK (role IN ('PRODUCT_MANAGER', 'COMPLIANCE_REVIEWER'))
);

COMMENT ON TABLE users IS '실제 사용자(상품 담당자/검토자). AI 소비자 Persona는 persona_templates에 저장한다.';

-- ============================== 02. PRODUCT ==================================

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT       NOT NULL REFERENCES users (id),
    name         VARCHAR(100) NOT NULL,
    product_type VARCHAR(20)  NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_products_type CHECK (product_type IN ('INVESTMENT', 'LOAN', 'SAVINGS'))
);

CREATE INDEX idx_products_owner ON products (owner_id);

COMMENT ON TABLE products IS '분석의 최상위 컨텍스트. status 컬럼 없음(확정).';

CREATE TABLE product_documents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    file_name      VARCHAR(255) NOT NULL,
    media_type     VARCHAR(150) NOT NULL,
    file_size      BIGINT,
    checksum       VARCHAR(64),
    storage_key    VARCHAR(500) NOT NULL,
    extract_status VARCHAR(20)  NOT NULL DEFAULT 'UPLOADED',
    extracted_text TEXT,
    confirmed      BOOLEAN      NOT NULL DEFAULT FALSE,
    confirmed_by   BIGINT REFERENCES users (id),
    confirmed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_product_documents_extract_status
        CHECK (extract_status IN ('UPLOADED', 'EXTRACTING', 'READY', 'FAILED'))
);

CREATE INDEX idx_product_documents_product ON product_documents (product_id);

COMMENT ON TABLE product_documents IS '파일 메타 + 추출 텍스트. 바이너리는 영구 저장하지 않으며 storage_key는 mock:// 포인터다.';
COMMENT ON COLUMN product_documents.checksum IS 'SHA-256 hex(64자). 업로드 스트림에서 계산하고 바이너리는 폐기한다.';

-- ========================= 03. CATALOG (Reference) ===========================

CREATE TABLE evidence_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(30)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    version     VARCHAR(50),
    content     TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_evidence_documents_source_type
        CHECK (source_type IN ('INTERNAL_POLICY', 'REGULATION', 'PRODUCT_POLICY'))
);

COMMENT ON TABLE evidence_documents IS '공식 승인 근거 라이브러리. 담당자는 선택만 한다.';

CREATE TABLE persona_templates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(40)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    criteria   JSONB,
    risk_focus JSONB,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_persona_templates_code CHECK (code IN (
        'FINANCIAL_BEGINNER', 'SENIOR', 'LOSS_EXPERIENCED',
        'SHORT_TERM_LIQUIDITY', 'SELF_EMPLOYED'
    ))
);

COMMENT ON TABLE persona_templates IS '고정 AI 소비자 Persona 5종(lookup). 시스템 사용자가 아니다.';

CREATE TABLE red_team_packs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(60)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE TABLE red_team_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL UNIQUE,
    pack_id     BIGINT       NOT NULL REFERENCES red_team_packs (id) ON DELETE CASCADE,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order  INT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_red_team_rules_code CHECK (code IN (
        'RETURN_FRAMING', 'LOSS_SOFTENING', 'COST_OMISSION',
        'STABILITY_KEYWORD', 'FORMAL_CONFIRMATION', 'COGNITIVE_ACCESSIBILITY'
    ))
);

CREATE INDEX idx_red_team_rules_pack ON red_team_rules (pack_id);

-- ============================= 04. ANALYSIS ==================================

CREATE TABLE analyses (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_document_id     BIGINT      NOT NULL REFERENCES product_documents (id),
    red_team_pack_id        BIGINT      NOT NULL REFERENCES red_team_packs (id),
    status                  VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    progress                INT         NOT NULL DEFAULT 0,
    risk_score              INT,
    model_version           VARCHAR(50),
    prompt_version          VARCHAR(50),
    requires_human_approval BOOLEAN     NOT NULL DEFAULT TRUE,
    retryable               BOOLEAN     NOT NULL DEFAULT FALSE,
    error_code              VARCHAR(60),
    completed_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL,
    input_hash              VARCHAR(64) NOT NULL,
    CONSTRAINT ck_analyses_status
        CHECK (status IN ('CREATED', 'RUNNING', 'COMPLETED', 'IN_REVIEW', 'FAILED')),
    CONSTRAINT ck_analyses_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT ck_analyses_risk_score CHECK (risk_score IS NULL OR risk_score BETWEEN 0 AND 100)
);

-- 내용 변화 없는 중복 재검증 차단. FAILED 분석은 재요청을 허용해야 하므로 제외한다.
CREATE UNIQUE INDEX ux_analyses_document_input_hash
    ON analyses (product_document_id, input_hash)
    WHERE status <> 'FAILED';

CREATE INDEX idx_analyses_document ON analyses (product_document_id);
CREATE INDEX idx_analyses_status ON analyses (status);

COMMENT ON COLUMN analyses.input_hash IS
    '분석 입력 지문 SHA-256 hex. confirmed extracted_text + red_team_pack_id + 정렬된 persona_id/evidence_document_id 목록을 서버가 정규화·해시한다.';

CREATE TABLE analysis_personas (
    analysis_id         BIGINT NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    persona_template_id BIGINT NOT NULL REFERENCES persona_templates (id),
    PRIMARY KEY (analysis_id, persona_template_id)
);

CREATE TABLE analysis_evidence_documents (
    analysis_id          BIGINT NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    evidence_document_id BIGINT NOT NULL REFERENCES evidence_documents (id),
    PRIMARY KEY (analysis_id, evidence_document_id)
);

CREATE TABLE findings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id    BIGINT      NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    statement      TEXT        NOT NULL,
    severity       VARCHAR(10) NOT NULL,
    recommendation TEXT,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_findings_severity CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW'))
);

CREATE INDEX idx_findings_analysis ON findings (analysis_id);

COMMENT ON TABLE findings IS 'HIGH Finding은 evidence_reference를 최소 1개 가져야 한다(앱 검증).';

CREATE TABLE finding_affected_personas (
    finding_id          BIGINT NOT NULL REFERENCES findings (id) ON DELETE CASCADE,
    persona_template_id BIGINT NOT NULL REFERENCES persona_templates (id),
    PRIMARY KEY (finding_id, persona_template_id)
);

CREATE TABLE evidence_references (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id           BIGINT      NOT NULL REFERENCES findings (id) ON DELETE CASCADE,
    evidence_document_id BIGINT      NOT NULL REFERENCES evidence_documents (id),
    excerpt              TEXT,
    created_at           TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_evidence_references_finding ON evidence_references (finding_id);

-- ============================== 05. REVIEW ===================================

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT       NOT NULL UNIQUE REFERENCES analyses (id) ON DELETE CASCADE,
    reviewer_id BIGINT REFERENCES users (id),
    status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    comment     VARCHAR(1000),
    decided_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_reviews_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_reviews_status ON reviews (status);

COMMENT ON TABLE reviews IS '분석당 1검토(UNIQUE). 결정은 별도 decision이 아니라 status에 통합한다.';

CREATE TABLE review_selected_findings (
    review_id  BIGINT NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    finding_id BIGINT NOT NULL REFERENCES findings (id) ON DELETE CASCADE,
    PRIMARY KEY (review_id, finding_id)
);

-- ========================= 06. RISK & GUARDFIT ===============================

CREATE TABLE risk_patterns (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT       NOT NULL UNIQUE REFERENCES findings (id),
    review_id  BIGINT REFERENCES reviews (id) ON DELETE SET NULL,
    name       VARCHAR(255) NOT NULL,
    severity   VARCHAR(10)  NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_risk_patterns_severity CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_risk_patterns_status CHECK (status IN ('DRAFT', 'ACTIVE'))
);

COMMENT ON TABLE risk_patterns IS '승인된 Finding만 승격한다. 영향 Persona/근거는 finding으로 역추적한다.';

CREATE TABLE guardfit_actions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_pattern_id BIGINT       NOT NULL REFERENCES risk_patterns (id) ON DELETE CASCADE,
    action_type     VARCHAR(20)  NOT NULL,
    label           VARCHAR(255) NOT NULL,
    placement       VARCHAR(255) NOT NULL,
    required        BOOLEAN      NOT NULL DEFAULT FALSE,
    preview         TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    updated_by      BIGINT REFERENCES users (id),
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_guardfit_actions_type
        CHECK (action_type IN ('LABEL', 'WARNING', 'QUESTION', 'COMPARISON')),
    CONSTRAINT ck_guardfit_actions_status CHECK (status IN ('DRAFT', 'APPROVED'))
);

CREATE INDEX idx_guardfit_actions_pattern ON guardfit_actions (risk_pattern_id);

COMMENT ON TABLE guardfit_actions IS 'WARNING_LABEL/DISCARDED는 사용하지 않는다(확정).';
