CREATE TABLE risk_score_runs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_execution_id BIGINT        NOT NULL REFERENCES analysis_executions (id),
    policy_version        VARCHAR(100)  NOT NULL,
    state                 VARCHAR(20)   NOT NULL,
    score_value           INTEGER,
    not_scored_reason     VARCHAR(500),
    input_fingerprint     VARCHAR(64)   NOT NULL,
    created_at            TIMESTAMPTZ   NOT NULL,
    completed_at          TIMESTAMPTZ,
    CONSTRAINT ux_risk_score_runs_idempotency
        UNIQUE (analysis_execution_id, policy_version, input_fingerprint),
    CONSTRAINT ck_risk_score_runs_policy_version
        CHECK (btrim(policy_version) <> ''),
    CONSTRAINT ck_risk_score_runs_state
        CHECK (state IN ('NOT_SCORED', 'PENDING_REVIEW', 'SCORED')),
    CONSTRAINT ck_risk_score_runs_input_fingerprint
        CHECK (input_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_risk_score_runs_result CHECK (
        (state = 'PENDING_REVIEW'
            AND score_value IS NULL
            AND not_scored_reason IS NULL
            AND completed_at IS NULL)
        OR
        (state = 'NOT_SCORED'
            AND score_value IS NULL
            AND not_scored_reason IS NOT NULL
            AND btrim(not_scored_reason) <> ''
            AND completed_at IS NOT NULL)
        OR
        (state = 'SCORED'
            AND score_value IS NOT NULL
            AND score_value BETWEEN 0 AND 100
            AND not_scored_reason IS NULL
            AND completed_at IS NOT NULL)
    ),
    CONSTRAINT ck_risk_score_runs_timestamp_order
        CHECK (completed_at IS NULL OR completed_at >= created_at)
);

CREATE INDEX idx_risk_score_runs_execution_created
    ON risk_score_runs (analysis_execution_id, created_at DESC, id DESC);

CREATE TABLE risk_score_ledger_entries (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_score_run_id            BIGINT        NOT NULL REFERENCES risk_score_runs (id),
    finding_revision_id          BIGINT        NOT NULL REFERENCES findings (id),
    finding_review_decision_id   BIGINT        NOT NULL REFERENCES finding_review_decisions (id),
    document_claim_anchor_id     BIGINT        NOT NULL REFERENCES finding_evidence_anchors (id),
    policy_requirement_anchor_id BIGINT        NOT NULL REFERENCES finding_evidence_anchors (id),
    policy_rule_id               VARCHAR(100)  NOT NULL,
    magnitude_basis_points       INTEGER       NOT NULL,
    likelihood_basis_points      INTEGER       NOT NULL,
    contribution_basis_points    INTEGER       NOT NULL,
    created_at                   TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ux_risk_score_ledger_entries_harm_event
        UNIQUE (risk_score_run_id, document_claim_anchor_id, policy_rule_id),
    CONSTRAINT ck_risk_score_ledger_entries_policy_rule
        CHECK (btrim(policy_rule_id) <> ''),
    CONSTRAINT ck_risk_score_ledger_entries_magnitude
        CHECK (magnitude_basis_points IN (2000, 4000, 6000, 8000, 10000)),
    CONSTRAINT ck_risk_score_ledger_entries_likelihood
        CHECK (likelihood_basis_points IN (2000, 4000, 6000, 8000, 10000)),
    CONSTRAINT ck_risk_score_ledger_entries_contribution CHECK (
        contribution_basis_points BETWEEN 0 AND 10000
        AND contribution_basis_points
            = (magnitude_basis_points * likelihood_basis_points) / 10000
    )
);

CREATE INDEX idx_risk_score_ledger_entries_run
    ON risk_score_ledger_entries (risk_score_run_id, id);

CREATE FUNCTION validate_risk_score_run()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM analysis_executions
        WHERE id = NEW.analysis_execution_id
          AND status = 'SUCCEEDED'
    ) THEN
        RAISE EXCEPTION 'risk score runs require a successful analysis execution'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_risk_score_runs_validate
BEFORE INSERT ON risk_score_runs
FOR EACH ROW
EXECUTE FUNCTION validate_risk_score_run();

CREATE FUNCTION validate_risk_score_ledger_entry()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    run_execution_id BIGINT;
    run_created_at TIMESTAMPTZ;
    run_completed_at TIMESTAMPTZ;
BEGIN
    SELECT analysis_execution_id, created_at, completed_at
    INTO run_execution_id, run_created_at, run_completed_at
    FROM risk_score_runs
    WHERE id = NEW.risk_score_run_id
      AND state = 'SCORED';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'ledger entries require a scored risk score run'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.created_at < run_created_at OR NEW.created_at > run_completed_at THEN
        RAISE EXCEPTION 'ledger entry timestamp must be within the score run time range'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM findings f
        WHERE f.id = NEW.finding_revision_id
          AND f.analysis_execution_id = run_execution_id
          AND f.lineage_id IS NOT NULL
          AND f.revision_number IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM findings successor
              WHERE successor.supersedes_finding_id = f.id
          )
    ) THEN
        RAISE EXCEPTION 'ledger finding must be a current revision from the score run execution'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM finding_review_decisions decision
        WHERE decision.id = NEW.finding_review_decision_id
          AND decision.analysis_execution_id = run_execution_id
          AND decision.finding_revision_id = NEW.finding_revision_id
          AND decision.decision = 'APPROVED'
    ) THEN
        RAISE EXCEPTION 'ledger finding must have the referenced reviewer approval'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM finding_evidence_anchors
        WHERE id = NEW.document_claim_anchor_id
          AND finding_id = NEW.finding_revision_id
          AND source_role = 'DOCUMENT_CLAIM'
    ) THEN
        RAISE EXCEPTION 'document claim anchor must belong to the ledger finding'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM finding_evidence_anchors
        WHERE id = NEW.policy_requirement_anchor_id
          AND finding_id = NEW.finding_revision_id
          AND source_role = 'POLICY_REQUIREMENT'
    ) THEN
        RAISE EXCEPTION 'policy requirement anchor must belong to the ledger finding'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_risk_score_ledger_entries_validate
BEFORE INSERT ON risk_score_ledger_entries
FOR EACH ROW
EXECUTE FUNCTION validate_risk_score_ledger_entry();

CREATE FUNCTION reject_risk_score_record_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% records are immutable', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_risk_score_runs_immutable
BEFORE UPDATE OR DELETE ON risk_score_runs
FOR EACH ROW
EXECUTE FUNCTION reject_risk_score_record_changes();

CREATE TRIGGER trg_risk_score_ledger_entries_immutable
BEFORE UPDATE OR DELETE ON risk_score_ledger_entries
FOR EACH ROW
EXECUTE FUNCTION reject_risk_score_record_changes();

COMMENT ON TABLE risk_score_runs IS
    'Immutable, policy-versioned score outcomes keyed idempotently to one analysis execution and input fingerprint.';
COMMENT ON TABLE risk_score_ledger_entries IS
    'Immutable evidence ledger containing only reviewer-approved current Finding revisions and policy-derived M/L components.';
COMMENT ON COLUMN risk_score_runs.input_fingerprint IS
    'Lowercase SHA-256 of the canonical score inputs; provider score, severity, personas, similarity, and model confidence are excluded.';
COMMENT ON COLUMN risk_score_ledger_entries.contribution_basis_points IS
    'Exact policy contribution: magnitude_basis_points multiplied by likelihood_basis_points and divided by 10000.';
