-- PostgreSQL rows are the authority for document batch scheduling. Application
-- events may wake workers, but they must never be used as queue state.

-- These covering keys allow ownership to be enforced by composite foreign keys
-- without changing the standalone product_documents lifecycle.
ALTER TABLE products
    ADD CONSTRAINT ux_products_id_owner UNIQUE (id, owner_id);

ALTER TABLE product_documents
    ADD CONSTRAINT ux_product_documents_id_product UNIQUE (id, product_id);

CREATE TABLE document_batches (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id           BIGINT       NOT NULL,
    owner_id             BIGINT       NOT NULL,
    scenario             VARCHAR(60)  NOT NULL,
    requested_item_count INTEGER      NOT NULL,
    idempotency_key      VARCHAR(200) NOT NULL,
    manifest_hash        VARCHAR(64)  NOT NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    cancel_requested_at  TIMESTAMPTZ,
    cancellation_reason  VARCHAR(500),
    cancelled_at         TIMESTAMPTZ,
    quarantine_reason    VARCHAR(500),
    quarantined_at       TIMESTAMPTZ,
    terminal_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_document_batches_product_owner
        FOREIGN KEY (product_id, owner_id) REFERENCES products (id, owner_id),
    CONSTRAINT ux_document_batches_id_product_owner
        UNIQUE (id, product_id, owner_id),
    CONSTRAINT ux_document_batches_owner_idempotency_key
        UNIQUE (owner_id, idempotency_key),
    CONSTRAINT ck_document_batches_requested_item_count
        CHECK (requested_item_count BETWEEN 1 AND 100),
    CONSTRAINT ck_document_batches_identity_fields
        CHECK (btrim(scenario) <> '' AND btrim(idempotency_key) <> ''),
    CONSTRAINT ck_document_batches_manifest_hash
        CHECK (manifest_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_batches_status
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'CANCELLED', 'QUARANTINED')),
    CONSTRAINT ck_document_batches_terminal
        CHECK ((status IN ('SUCCEEDED', 'CANCELLED', 'QUARANTINED')) = (terminal_at IS NOT NULL)),
    CONSTRAINT ck_document_batches_cancellation_fields
        CHECK (
            (cancel_requested_at IS NULL) = (cancellation_reason IS NULL)
            AND (status <> 'CANCELLED' OR cancellation_reason IS NOT NULL)
            AND ((status = 'CANCELLED') = (cancelled_at IS NOT NULL))
            AND (cancelled_at IS NULL OR (
                cancelled_at = terminal_at AND cancelled_at >= cancel_requested_at
            ))
        ),
    CONSTRAINT ck_document_batches_quarantine_fields
        CHECK (
            (
                status = 'QUARANTINED'
                AND quarantine_reason IS NOT NULL
                AND quarantined_at IS NOT NULL
                AND quarantined_at = terminal_at
            )
            OR
            (
                status <> 'QUARANTINED'
                AND quarantine_reason IS NULL
                AND quarantined_at IS NULL
            )
        )
);

CREATE INDEX idx_document_batches_product_created
    ON document_batches (product_id, created_at DESC);

CREATE INDEX idx_document_batches_owner_status
    ON document_batches (owner_id, status);

CREATE TABLE document_batch_items (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id              BIGINT        NOT NULL,
    product_id            BIGINT        NOT NULL,
    owner_id              BIGINT        NOT NULL,
    product_document_id   BIGINT        NOT NULL,
    ordinal               INTEGER       NOT NULL,
    source_file_name      VARCHAR(255)  NOT NULL,
    source_media_type     VARCHAR(150)  NOT NULL,
    source_file_size      BIGINT        NOT NULL,
    source_checksum       VARCHAR(64)   NOT NULL,
    source_storage_key    VARCHAR(500)  NOT NULL,
    due_at                TIMESTAMPTZ   NOT NULL,
    attempt_count         INTEGER       NOT NULL DEFAULT 0,
    max_attempts          INTEGER       NOT NULL DEFAULT 3,
    status                VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    lease_owner           VARCHAR(100),
    lease_until           TIMESTAMPTZ,
    lease_fence           BIGINT        NOT NULL DEFAULT 0,
    cancel_requested_at   TIMESTAMPTZ,
    cancellation_reason   VARCHAR(500),
    cancelled_at          TIMESTAMPTZ,
    last_error_code       VARCHAR(60),
    last_error_message    VARCHAR(1000),
    quarantine_reason     VARCHAR(500),
    quarantined_at        TIMESTAMPTZ,
    terminal_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ   NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_document_batch_items_batch_owner
        FOREIGN KEY (batch_id, product_id, owner_id)
        REFERENCES document_batches (id, product_id, owner_id) ON DELETE CASCADE,
    CONSTRAINT fk_document_batch_items_document_product
        FOREIGN KEY (product_document_id, product_id)
        REFERENCES product_documents (id, product_id),
    CONSTRAINT ux_document_batch_items_batch_ordinal
        UNIQUE (batch_id, ordinal),
    CONSTRAINT ux_document_batch_items_batch_document
        UNIQUE (batch_id, product_document_id),
    CONSTRAINT ck_document_batch_items_ordinal
        CHECK (ordinal BETWEEN 1 AND 100),
    CONSTRAINT ck_document_batch_items_source_file_size
        CHECK (source_file_size >= 0),
    CONSTRAINT ck_document_batch_items_source_metadata
        CHECK (
            btrim(source_file_name) <> ''
            AND btrim(source_media_type) <> ''
            AND btrim(source_storage_key) <> ''
        ),
    CONSTRAINT ck_document_batch_items_source_checksum
        CHECK (source_checksum ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_batch_items_attempts
        CHECK (max_attempts BETWEEN 1 AND 100 AND attempt_count BETWEEN 0 AND max_attempts),
    CONSTRAINT ck_document_batch_items_status
        CHECK (status IN (
            'PENDING', 'LEASED', 'RETRY_WAIT',
            'SUCCEEDED', 'CANCELLED', 'QUARANTINED'
        )),
    CONSTRAINT ck_document_batch_items_lease
        CHECK (
            (
                (status = 'LEASED' AND lease_owner IS NOT NULL AND lease_until IS NOT NULL)
                OR
                (status <> 'LEASED' AND lease_owner IS NULL AND lease_until IS NULL)
            )
            AND lease_fence >= 0
            AND (status <> 'LEASED' OR attempt_count > 0)
        ),
    CONSTRAINT ck_document_batch_items_terminal
        CHECK ((status IN ('SUCCEEDED', 'CANCELLED', 'QUARANTINED')) = (terminal_at IS NOT NULL)),
    CONSTRAINT ck_document_batch_items_cancellation_fields
        CHECK (
            (cancel_requested_at IS NULL) = (cancellation_reason IS NULL)
            AND (status <> 'CANCELLED' OR cancellation_reason IS NOT NULL)
            AND ((status = 'CANCELLED') = (cancelled_at IS NOT NULL))
            AND (cancelled_at IS NULL OR (
                cancelled_at = terminal_at AND cancelled_at >= cancel_requested_at
            ))
        ),
    CONSTRAINT ck_document_batch_items_quarantine_fields
        CHECK (
            (
                status = 'QUARANTINED'
                AND quarantine_reason IS NOT NULL
                AND quarantined_at IS NOT NULL
                AND quarantined_at = terminal_at
            )
            OR
            (
                status <> 'QUARANTINED'
                AND quarantine_reason IS NULL
                AND quarantined_at IS NULL
            )
        ),
    CONSTRAINT ck_document_batch_items_error_fields
        CHECK ((last_error_code IS NULL) = (last_error_message IS NULL))
);

-- Claimers select due rows ordered by due_at/id with FOR UPDATE SKIP LOCKED.
-- The partial index keeps terminal and currently leased rows out of that scan.
CREATE INDEX idx_document_batch_items_due_claim
    ON document_batch_items (due_at, id)
    WHERE status IN ('PENDING', 'RETRY_WAIT');

-- Recovery scans only leases whose deadline may have passed. lease_fence is
-- checked by every worker transition so a recovered stale worker cannot write.
CREATE INDEX idx_document_batch_items_expired_lease
    ON document_batch_items (lease_until, id)
    WHERE status = 'LEASED';

CREATE INDEX idx_document_batch_items_batch_status
    ON document_batch_items (batch_id, status, ordinal);

CREATE INDEX idx_document_batch_items_owner_status
    ON document_batch_items (owner_id, status);

CREATE TABLE document_batch_item_attempts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id              BIGINT       NOT NULL REFERENCES document_batch_items (id) ON DELETE CASCADE,
    attempt_no           INTEGER      NOT NULL,
    lease_fence          BIGINT       NOT NULL,
    worker_owner         VARCHAR(100) NOT NULL,
    started_at           TIMESTAMPTZ  NOT NULL,
    ended_at             TIMESTAMPTZ,
    outcome              VARCHAR(30),
    public_error_code    VARCHAR(60),
    public_error_message VARCHAR(1000),
    diagnostic_reference VARCHAR(255),

    CONSTRAINT ux_document_batch_item_attempts_item_attempt
        UNIQUE (item_id, attempt_no),
    CONSTRAINT ck_document_batch_item_attempts_number
        CHECK (attempt_no > 0 AND lease_fence > 0),
    CONSTRAINT ck_document_batch_item_attempts_completion
        CHECK ((ended_at IS NULL) = (outcome IS NULL)),
    CONSTRAINT ck_document_batch_item_attempts_error
        CHECK ((public_error_code IS NULL) = (public_error_message IS NULL)),
    CONSTRAINT ck_document_batch_item_attempts_outcome
        CHECK (outcome IS NULL OR outcome IN (
            'SUCCEEDED', 'RETRY_WAIT', 'QUARANTINED', 'CANCELLED',
            'LEASE_EXPIRED_RETRY', 'LEASE_EXPIRED_QUARANTINED',
            'LEASE_EXPIRED_CANCELLED'
        ))
);

CREATE INDEX idx_document_batch_item_attempts_item
    ON document_batch_item_attempts (item_id, attempt_no);

CREATE OR REPLACE FUNCTION guard_document_batch_item_attempt_mutation()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'document_batch_item_attempts cannot be deleted';
    END IF;
    IF OLD.ended_at IS NOT NULL
       OR NEW.item_id <> OLD.item_id
       OR NEW.attempt_no <> OLD.attempt_no
       OR NEW.lease_fence <> OLD.lease_fence
       OR NEW.worker_owner <> OLD.worker_owner
       OR NEW.started_at <> OLD.started_at
       OR NEW.ended_at IS NULL THEN
        RAISE EXCEPTION 'document_batch_item_attempts can only be completed once';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER document_batch_item_attempts_completion_only
BEFORE UPDATE OR DELETE ON document_batch_item_attempts
FOR EACH ROW EXECUTE FUNCTION guard_document_batch_item_attempt_mutation();

COMMENT ON TABLE document_batches IS
    'Durable document submission identity and aggregate lifecycle; rows, not application events, are authoritative.';
COMMENT ON COLUMN document_batches.manifest_hash IS
    'SHA-256 of the canonical ordered upload manifest; paired with owner-scoped idempotency_key.';
COMMENT ON TABLE document_batch_items IS
    'Durable item queue with immutable source snapshot, due time, retry state, and fenced lease.';
COMMENT ON COLUMN document_batch_items.lease_fence IS
    'Monotonically incremented on each claim; a worker update must match both lease_owner and lease_fence.';
