CREATE TABLE document_extraction_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_document_id BIGINT       NOT NULL
        REFERENCES product_documents (id) ON DELETE CASCADE,
    run_generation      INTEGER      NOT NULL,
    source_hash         VARCHAR(64)  NOT NULL,
    config_version      VARCHAR(100) NOT NULL,
    config_snapshot     JSONB        NOT NULL,
    state               VARCHAR(20)  NOT NULL,
    result_text_hash    VARCHAR(64),
    page_count          INTEGER      NOT NULL,
    error_code          VARCHAR(60),
    error_message       VARCHAR(500),
    error_retryable     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_document_extraction_runs_document_generation
        UNIQUE (product_document_id, run_generation),
    CONSTRAINT ux_document_extraction_runs_id_document
        UNIQUE (id, product_document_id),
    CONSTRAINT ck_document_extraction_runs_generation
        CHECK (run_generation > 0),
    CONSTRAINT ck_document_extraction_runs_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_extraction_runs_config_version
        CHECK (btrim(config_version) <> ''),
    CONSTRAINT ck_document_extraction_runs_config_snapshot
        CHECK (jsonb_typeof(config_snapshot) = 'object'),
    CONSTRAINT ck_document_extraction_runs_state
        CHECK (state IN ('SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_document_extraction_runs_result_hash
        CHECK (result_text_hash IS NULL OR result_text_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_extraction_runs_page_count
        CHECK (page_count >= 0),
    CONSTRAINT ck_document_extraction_runs_outcome
        CHECK (
            (state = 'SUCCEEDED'
                AND result_text_hash IS NOT NULL
                AND page_count > 0
                AND error_code IS NULL
                AND error_message IS NULL
                AND error_retryable = FALSE)
            OR
            (state = 'FAILED'
                AND result_text_hash IS NULL
                AND error_code IS NOT NULL
                AND btrim(error_code) <> ''
                AND error_message IS NOT NULL
                AND btrim(error_message) <> '')
        )
);

CREATE INDEX idx_document_extraction_runs_document_created
    ON document_extraction_runs (product_document_id, created_at DESC);
CREATE INDEX idx_document_extraction_runs_source_hash
    ON document_extraction_runs (source_hash);

CREATE TABLE document_extraction_pages (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extraction_run_id          BIGINT       NOT NULL
        REFERENCES document_extraction_runs (id) ON DELETE CASCADE,
    page_number                INTEGER      NOT NULL,
    selected_method            VARCHAR(30)  NOT NULL,
    selected_text              TEXT         NOT NULL,
    selected_text_hash         VARCHAR(64)  NOT NULL,
    pdfbox_candidate_hash      VARCHAR(64)  NOT NULL,
    ocr_render_artifact_key    VARCHAR(500),
    ocr_render_artifact_hash   VARCHAR(64),
    ocr_config_snapshot        JSONB,
    ocr_engine                 VARCHAR(100),
    ocr_model_version          VARCHAR(150),
    ocr_language               VARCHAR(50),
    ocr_confidence             NUMERIC(7, 4),
    ocr_warnings               JSONB,
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_document_extraction_pages_run_page
        UNIQUE (extraction_run_id, page_number),
    CONSTRAINT ck_document_extraction_pages_page_number
        CHECK (page_number > 0),
    CONSTRAINT ck_document_extraction_pages_method
        CHECK (selected_method IN ('PDFBOX_TEXT', 'OCR_KOR_ENG')),
    CONSTRAINT ck_document_extraction_pages_selected_hash
        CHECK (selected_text_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_extraction_pages_pdfbox_hash
        CHECK (pdfbox_candidate_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_extraction_pages_ocr_render_hash
        CHECK (ocr_render_artifact_hash IS NULL OR ocr_render_artifact_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_extraction_pages_ocr_config
        CHECK (ocr_config_snapshot IS NULL OR jsonb_typeof(ocr_config_snapshot) = 'object'),
    CONSTRAINT ck_document_extraction_pages_ocr_confidence
        CHECK (ocr_confidence IS NULL OR ocr_confidence BETWEEN 0 AND 100),
    CONSTRAINT ck_document_extraction_pages_ocr_warnings
        CHECK (ocr_warnings IS NULL OR jsonb_typeof(ocr_warnings) = 'array'),
    CONSTRAINT ck_document_extraction_pages_method_metadata
        CHECK (
            (selected_method = 'PDFBOX_TEXT'
                AND ocr_render_artifact_key IS NULL
                AND ocr_render_artifact_hash IS NULL
                AND ocr_config_snapshot IS NULL
                AND ocr_engine IS NULL
                AND ocr_model_version IS NULL
                AND ocr_language IS NULL
                AND ocr_confidence IS NULL
                AND ocr_warnings IS NULL)
            OR
            (selected_method = 'OCR_KOR_ENG'
                AND ocr_render_artifact_key IS NOT NULL
                AND btrim(ocr_render_artifact_key) <> ''
                AND ocr_render_artifact_hash IS NOT NULL
                AND ocr_config_snapshot IS NOT NULL
                AND ocr_engine IS NOT NULL
                AND btrim(ocr_engine) <> ''
                AND ocr_model_version IS NOT NULL
                AND btrim(ocr_model_version) <> ''
                AND ocr_language IS NOT NULL
                AND btrim(ocr_language) <> ''
                AND ocr_confidence IS NOT NULL
                AND ocr_warnings IS NOT NULL)
        )
);

ALTER TABLE product_documents
    ADD COLUMN current_extraction_run_id BIGINT,
    ADD COLUMN extracted_text_hash VARCHAR(64),
    ADD COLUMN confirmed_extraction_run_id BIGINT,
    ADD COLUMN confirmed_text_hash VARCHAR(64),
    ADD CONSTRAINT fk_product_documents_current_extraction_run
        FOREIGN KEY (current_extraction_run_id, id)
        REFERENCES document_extraction_runs (id, product_document_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_product_documents_confirmed_extraction_run
        FOREIGN KEY (confirmed_extraction_run_id, id)
        REFERENCES document_extraction_runs (id, product_document_id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT ck_product_documents_extracted_text_hash
        CHECK (extracted_text_hash IS NULL OR extracted_text_hash ~ '^[0-9a-f]{64}$'),
    ADD CONSTRAINT ck_product_documents_confirmed_text_hash
        CHECK (confirmed_text_hash IS NULL OR confirmed_text_hash ~ '^[0-9a-f]{64}$'),
    ADD CONSTRAINT ck_product_documents_confirmation_binding
        CHECK (
            current_extraction_run_id IS NULL
            OR
            (confirmed = FALSE
                AND confirmed_extraction_run_id IS NULL
                AND confirmed_text_hash IS NULL)
            OR
            (confirmed = TRUE
                AND confirmed_by IS NOT NULL
                AND confirmed_at IS NOT NULL
                AND confirmed_extraction_run_id IS NOT DISTINCT FROM current_extraction_run_id
                AND confirmed_text_hash IS NOT NULL
                AND extracted_text_hash IS NOT NULL
                AND confirmed_text_hash = extracted_text_hash)
        ) NOT VALID;

COMMENT ON TABLE document_extraction_runs IS
    'Append-only terminal extraction attempts; each generation records its exact source and configuration.';
COMMENT ON TABLE document_extraction_pages IS
    'Append-only ordered page provenance for the PDFBox or Korean/English OCR text selected by a run.';
COMMENT ON COLUMN product_documents.current_extraction_run_id IS
    'Nullable for legacy documents; identifies the run that produced the current extracted text.';
COMMENT ON COLUMN product_documents.confirmed_text_hash IS
    'Exact extracted-text SHA-256 acknowledged by the confirmer; pre-V24 legacy rows remain unbackfilled.';

CREATE FUNCTION reject_document_extraction_run_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
        OR EXISTS (
            SELECT 1
            FROM product_documents
            WHERE id = OLD.product_document_id
        )
    THEN
        RAISE EXCEPTION 'document_extraction_runs records are immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN OLD;
END;
$$;

CREATE TRIGGER trg_document_extraction_runs_immutable
BEFORE UPDATE OR DELETE ON document_extraction_runs
FOR EACH ROW
EXECUTE FUNCTION reject_document_extraction_run_changes();

CREATE FUNCTION reject_document_extraction_page_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
        OR EXISTS (
            SELECT 1
            FROM document_extraction_runs
            WHERE id = OLD.extraction_run_id
        )
    THEN
        RAISE EXCEPTION 'document_extraction_pages records are immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN OLD;
END;
$$;

CREATE TRIGGER trg_document_extraction_pages_immutable
BEFORE UPDATE OR DELETE ON document_extraction_pages
FOR EACH ROW
EXECUTE FUNCTION reject_document_extraction_page_changes();
