CREATE TABLE audit_events (
    audit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trace_id      VARCHAR(64)  NOT NULL,
    actor_id      BIGINT,
    action        VARCHAR(32)  NOT NULL,
    resource_type VARCHAR(20)  NOT NULL,
    resource_id   BIGINT       NOT NULL,
    resource_label VARCHAR(255),
    analysis_id   BIGINT,
    CONSTRAINT ck_audit_events_action CHECK (action IN (
        'ANALYSIS_CREATED',
        'ANALYSIS_RETRIED',
        'ANALYSIS_COMPLETED',
        'ANALYSIS_FAILED',
        'REVIEW_CREATED',
        'REVIEW_APPROVED',
        'REVIEW_REJECTED',
        'RISK_PATTERN_PROMOTED',
        'RISK_PATTERN_UPDATED',
        'RISK_PATTERN_ACTIVATED',
        'GUARDFIT_ACTION_CREATED',
        'GUARDFIT_ACTION_UPDATED',
        'GUARDFIT_ACTION_APPROVED'
    )),
    CONSTRAINT ck_audit_events_resource_type CHECK (resource_type IN (
        'ANALYSIS',
        'REVIEW',
        'RISK_PATTERN',
        'GUARDFIT_ACTION'
    )),
    CONSTRAINT ck_audit_events_action_resource_type CHECK (
        (action IN (
            'ANALYSIS_CREATED',
            'ANALYSIS_RETRIED',
            'ANALYSIS_COMPLETED',
            'ANALYSIS_FAILED'
        ) AND resource_type = 'ANALYSIS')
        OR (action IN (
            'REVIEW_CREATED',
            'REVIEW_APPROVED',
            'REVIEW_REJECTED'
        ) AND resource_type = 'REVIEW')
        OR (action IN (
            'RISK_PATTERN_PROMOTED',
            'RISK_PATTERN_UPDATED',
            'RISK_PATTERN_ACTIVATED'
        ) AND resource_type = 'RISK_PATTERN')
        OR (action IN (
            'GUARDFIT_ACTION_CREATED',
            'GUARDFIT_ACTION_UPDATED',
            'GUARDFIT_ACTION_APPROVED'
        ) AND resource_type = 'GUARDFIT_ACTION')
    )
);

CREATE INDEX idx_audit_events_created_at_audit_id
    ON audit_events (created_at DESC, audit_id DESC);

CREATE FUNCTION reject_audit_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only';
END;
$$;

CREATE TRIGGER trg_audit_events_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_events
FOR EACH STATEMENT
EXECUTE FUNCTION reject_audit_event_mutation();
