CREATE TABLE ground_truth_facts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT       NOT NULL REFERENCES product_documents (id) ON DELETE CASCADE,
    label               VARCHAR(255) NOT NULL,
    value               TEXT         NOT NULL,
    importance          VARCHAR(10)  NOT NULL,
    verification_status VARCHAR(20)  NOT NULL,
    extraction_source   VARCHAR(30)  NOT NULL,
    source_text_sha256  VARCHAR(64)  NOT NULL,
    created_by          BIGINT       NOT NULL REFERENCES users (id),
    decided_by          BIGINT REFERENCES users (id),
    decided_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ux_ground_truth_facts_document UNIQUE (document_id),
    CONSTRAINT ck_ground_truth_facts_importance
        CHECK (importance = 'HIGH'),
    CONSTRAINT ck_ground_truth_facts_verification_status
        CHECK (verification_status IN ('CANDIDATE', 'VERIFIED', 'REJECTED')),
    CONSTRAINT ck_ground_truth_facts_extraction_source
        CHECK (extraction_source = 'CONFIRMED_DOCUMENT'),
    CONSTRAINT ck_ground_truth_facts_source_text_sha256
        CHECK (source_text_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_ground_truth_facts_decision
        CHECK (
            (verification_status = 'CANDIDATE' AND decided_by IS NULL AND decided_at IS NULL)
            OR
            (verification_status IN ('VERIFIED', 'REJECTED') AND decided_by IS NOT NULL AND decided_at IS NOT NULL)
        )
);

COMMENT ON TABLE ground_truth_facts IS
    '담당자가 확인한 product_document 원문 전체의 현재 공식 사실 스냅샷. 문서당 한 건만 유지한다.';
COMMENT ON COLUMN ground_truth_facts.value IS
    'AI 요약이나 fixture가 아닌 product_documents.extracted_text의 사람 확인 당시 원문.';
COMMENT ON COLUMN ground_truth_facts.source_text_sha256 IS
    'value 원문의 SHA-256 lowercase hex. 확인 텍스트 변경 여부를 판별한다.';
