CREATE TABLE analysis_ground_truth_fact_snapshots (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id          BIGINT       NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    ground_truth_fact_id BIGINT       NOT NULL REFERENCES ground_truth_facts (id),
    label                VARCHAR(255) NOT NULL,
    value                TEXT         NOT NULL,
    CONSTRAINT ux_analysis_ground_truth_fact_snapshots_fact
        UNIQUE (analysis_id, ground_truth_fact_id)
);

CREATE INDEX idx_analysis_ground_truth_fact_snapshots_analysis
    ON analysis_ground_truth_fact_snapshots (analysis_id);

COMMENT ON TABLE analysis_ground_truth_fact_snapshots IS
    '분석 수락 시점의 검증된 공식 사실 label/value 불변 복사본.';
