CREATE TABLE idempotency_claims (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id            BIGINT       NOT NULL REFERENCES users (id),
    operation           VARCHAR(32)  NOT NULL,
    idempotency_key     VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64)  NOT NULL,
    analysis_id         BIGINT REFERENCES analyses (id),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_idempotency_claims_operation
        CHECK (operation IN ('ANALYSIS_CREATE')),
    CONSTRAINT ck_idempotency_claims_request_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ux_idempotency_claims_actor_operation_key
        UNIQUE (actor_id, operation, idempotency_key)
);

COMMENT ON TABLE idempotency_claims IS
    '사용자별 분석 생성 멱등성 선점. analysis_id가 채워지면 승자 요청이 완료된 상태다.';
COMMENT ON COLUMN idempotency_claims.request_fingerprint IS
    '정규화된 분석 생성 요청의 lowercase SHA-256 hex.';
