CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE evidence_document_chunks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_document_id BIGINT       NOT NULL REFERENCES evidence_documents (id) ON DELETE CASCADE,
    source_hash          VARCHAR(64)  NOT NULL,
    chunk_ordinal        INTEGER      NOT NULL,
    chunking_version     VARCHAR(100) NOT NULL,
    chunk_hash           VARCHAR(64)  NOT NULL,
    chunk_text           TEXT         NOT NULL,
    embedding_model      VARCHAR(255) NOT NULL,
    embedding            vector(1024) NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_evidence_document_chunks_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_evidence_document_chunks_ordinal
        CHECK (chunk_ordinal >= 0),
    CONSTRAINT ck_evidence_document_chunks_chunking_version
        CHECK (btrim(chunking_version) <> ''),
    CONSTRAINT ck_evidence_document_chunks_chunk_hash
        CHECK (chunk_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_evidence_document_chunks_text
        CHECK (btrim(chunk_text) <> ''),
    CONSTRAINT ck_evidence_document_chunks_embedding_model
        CHECK (btrim(embedding_model) <> ''),
    CONSTRAINT ux_evidence_document_chunks_identity
        UNIQUE (evidence_document_id, source_hash, chunking_version, embedding_model, chunk_ordinal),
    CONSTRAINT ux_evidence_document_chunks_id_document
        UNIQUE (id, evidence_document_id)
);

CREATE INDEX idx_evidence_document_chunks_document
    ON evidence_document_chunks (evidence_document_id);

CREATE INDEX idx_evidence_document_chunks_source_hash
    ON evidence_document_chunks (source_hash);

CREATE INDEX idx_evidence_document_chunks_embedding_cosine
    ON evidence_document_chunks
    USING hnsw (embedding vector_cosine_ops);

COMMENT ON TABLE evidence_document_chunks IS
    'Deterministically versioned evidence chunks and their Ollama embeddings for pgvector retrieval.';
COMMENT ON COLUMN evidence_document_chunks.source_hash IS
    'Lowercase SHA-256 hex of the complete source text used for this indexing pass.';
COMMENT ON COLUMN evidence_document_chunks.chunk_hash IS
    'Lowercase SHA-256 hex of chunk_text.';
