CREATE TABLE analysis_rag_runs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id          BIGINT       NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    query_hash           VARCHAR(64)  NOT NULL,
    embedding_model      VARCHAR(255) NOT NULL,
    retrieval_version    VARCHAR(100) NOT NULL,
    requested_result_count INTEGER    NOT NULL,
    retrieved_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_analysis_rag_runs_analysis UNIQUE (analysis_id),
    CONSTRAINT ck_analysis_rag_runs_query_hash
        CHECK (query_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_analysis_rag_runs_embedding_model
        CHECK (btrim(embedding_model) <> ''),
    CONSTRAINT ck_analysis_rag_runs_retrieval_version
        CHECK (btrim(retrieval_version) <> ''),
    CONSTRAINT ck_analysis_rag_runs_requested_result_count
        CHECK (requested_result_count > 0)
);

CREATE TABLE analysis_rag_retrieval_snapshots (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rag_run_id                 BIGINT           NOT NULL REFERENCES analysis_rag_runs (id) ON DELETE CASCADE,
    rank                       INTEGER          NOT NULL,
    evidence_document_id       BIGINT           NOT NULL REFERENCES evidence_documents (id),
    evidence_document_chunk_id BIGINT           NOT NULL,
    source_hash                VARCHAR(64)      NOT NULL,
    chunk_hash                 VARCHAR(64)      NOT NULL,
    chunk_text                 TEXT             NOT NULL,
    similarity                 DOUBLE PRECISION NOT NULL,
    created_at                 TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_rag_snapshots_chunk_document
        FOREIGN KEY (evidence_document_chunk_id, evidence_document_id)
        REFERENCES evidence_document_chunks (id, evidence_document_id),
    CONSTRAINT ux_analysis_rag_snapshots_rank UNIQUE (rag_run_id, rank),
    CONSTRAINT ux_analysis_rag_snapshots_chunk UNIQUE (rag_run_id, evidence_document_chunk_id),
    CONSTRAINT ck_analysis_rag_snapshots_rank CHECK (rank > 0),
    CONSTRAINT ck_analysis_rag_snapshots_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_analysis_rag_snapshots_chunk_hash
        CHECK (chunk_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_analysis_rag_snapshots_text
        CHECK (btrim(chunk_text) <> ''),
    CONSTRAINT ck_analysis_rag_snapshots_similarity
        CHECK (similarity >= -1.0 AND similarity <= 1.0)
);

CREATE INDEX idx_analysis_rag_snapshots_run
    ON analysis_rag_retrieval_snapshots (rag_run_id);

CREATE INDEX idx_analysis_rag_snapshots_document
    ON analysis_rag_retrieval_snapshots (evidence_document_id);

COMMENT ON TABLE analysis_rag_runs IS
    'Immutable retrieval configuration and query fingerprint captured once per analysis.';
COMMENT ON TABLE analysis_rag_retrieval_snapshots IS
    'Immutable ranked copies of retrieved evidence chunks used by an analysis.';
COMMENT ON COLUMN analysis_rag_retrieval_snapshots.similarity IS
    'Cosine similarity recorded at retrieval time; larger values are more similar.';
