--
-- PostgreSQL database dump
--

\restrict tsodcdmk6SyUUqd1WW45XMggaPNwPMzsxYBXi9i8znBwtCw4PJcAYsJV4nAAEaD

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: reject_analysis_rag_run_changes(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reject_analysis_rag_run_changes() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'analysis_rag_runs records are immutable'
            USING ERRCODE = '55000';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM analyses
        WHERE id = OLD.analysis_id
          AND status <> 'RUNNING'
    ) THEN
        RAISE EXCEPTION 'completed analysis_rag_runs records are immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN OLD;
END;
$$;


--
-- Name: reject_analysis_rag_snapshot_changes(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reject_analysis_rag_snapshot_changes() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'analysis_rag_retrieval_snapshots records are immutable'
            USING ERRCODE = '55000';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM analysis_rag_runs run
        JOIN analyses analysis ON analysis.id = run.analysis_id
        WHERE run.id = OLD.rag_run_id
          AND analysis.status <> 'RUNNING'
    ) THEN
        RAISE EXCEPTION 'completed analysis_rag_retrieval_snapshots records are immutable'
            USING ERRCODE = '55000';
    END IF;

    RETURN OLD;
END;
$$;


--
-- Name: reject_audit_event_mutation(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reject_audit_event_mutation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only';
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analyses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analyses (
    id bigint NOT NULL,
    product_document_id bigint NOT NULL,
    red_team_pack_id bigint NOT NULL,
    status character varying(20) DEFAULT 'CREATED'::character varying NOT NULL,
    progress integer DEFAULT 0 NOT NULL,
    risk_score integer,
    model_version character varying(50),
    prompt_version character varying(50),
    requires_human_approval boolean DEFAULT true NOT NULL,
    retryable boolean DEFAULT false NOT NULL,
    error_code character varying(60),
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    input_hash character varying(64) NOT NULL,
    execution_token character varying(36) DEFAULT 'not-started'::character varying NOT NULL,
    CONSTRAINT ck_analyses_progress CHECK (((progress >= 0) AND (progress <= 100))),
    CONSTRAINT ck_analyses_risk_score CHECK (((risk_score IS NULL) OR ((risk_score >= 0) AND (risk_score <= 100)))),
    CONSTRAINT ck_analyses_status CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'IN_REVIEW'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: COLUMN analyses.input_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.analyses.input_hash IS '분석 입력 지문 SHA-256 hex. confirmed extracted_text + red_team_pack_id + 정렬된 persona_id/evidence_document_id 목록을 서버가 정규화·해시한다.';


--
-- Name: analyses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_evidence_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_evidence_documents (
    analysis_id bigint NOT NULL,
    evidence_document_id bigint NOT NULL
);


--
-- Name: analysis_ground_truth_fact_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_ground_truth_fact_snapshots (
    id bigint NOT NULL,
    analysis_id bigint NOT NULL,
    ground_truth_fact_id bigint NOT NULL,
    label character varying(255) NOT NULL,
    value text NOT NULL
);


--
-- Name: TABLE analysis_ground_truth_fact_snapshots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.analysis_ground_truth_fact_snapshots IS '분석 수락 시점의 검증된 공식 사실 label/value 불변 복사본.';


--
-- Name: analysis_ground_truth_fact_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analysis_ground_truth_fact_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_ground_truth_fact_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_personas (
    analysis_id bigint NOT NULL,
    persona_template_id bigint NOT NULL
);


--
-- Name: analysis_rag_retrieval_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_rag_retrieval_snapshots (
    id bigint NOT NULL,
    rag_run_id bigint NOT NULL,
    rank integer NOT NULL,
    evidence_document_id bigint NOT NULL,
    evidence_document_chunk_id bigint NOT NULL,
    source_hash character varying(64) NOT NULL,
    chunk_hash character varying(64) NOT NULL,
    chunk_text text NOT NULL,
    similarity double precision NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_analysis_rag_snapshots_chunk_hash CHECK (((chunk_hash)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_analysis_rag_snapshots_rank CHECK ((rank > 0)),
    CONSTRAINT ck_analysis_rag_snapshots_similarity CHECK (((similarity >= ('-1.0'::numeric)::double precision) AND (similarity <= (1.0)::double precision))),
    CONSTRAINT ck_analysis_rag_snapshots_source_hash CHECK (((source_hash)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_analysis_rag_snapshots_text CHECK ((btrim(chunk_text) <> ''::text))
);


--
-- Name: TABLE analysis_rag_retrieval_snapshots; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.analysis_rag_retrieval_snapshots IS 'Immutable ranked copies of retrieved evidence chunks used by an analysis.';


--
-- Name: COLUMN analysis_rag_retrieval_snapshots.similarity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.analysis_rag_retrieval_snapshots.similarity IS 'Cosine similarity recorded at retrieval time; larger values are more similar.';


--
-- Name: analysis_rag_retrieval_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analysis_rag_retrieval_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_rag_retrieval_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_rag_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_rag_runs (
    id bigint NOT NULL,
    analysis_id bigint NOT NULL,
    query_hash character varying(64) NOT NULL,
    embedding_model character varying(255) NOT NULL,
    retrieval_version character varying(100) NOT NULL,
    requested_result_count integer NOT NULL,
    retrieved_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_analysis_rag_runs_embedding_model CHECK ((btrim((embedding_model)::text) <> ''::text)),
    CONSTRAINT ck_analysis_rag_runs_query_hash CHECK (((query_hash)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_analysis_rag_runs_requested_result_count CHECK ((requested_result_count > 0)),
    CONSTRAINT ck_analysis_rag_runs_retrieval_version CHECK ((btrim((retrieval_version)::text) <> ''::text))
);


--
-- Name: TABLE analysis_rag_runs; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.analysis_rag_runs IS 'Immutable retrieval configuration and query fingerprint captured once per analysis.';


--
-- Name: analysis_rag_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analysis_rag_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_rag_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    audit_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    trace_id character varying(64) NOT NULL,
    actor_id bigint,
    action character varying(32) NOT NULL,
    resource_type character varying(20) NOT NULL,
    resource_id bigint NOT NULL,
    resource_label character varying(255),
    analysis_id bigint,
    CONSTRAINT ck_audit_events_action CHECK (((action)::text = ANY ((ARRAY['ANALYSIS_CREATED'::character varying, 'ANALYSIS_RETRIED'::character varying, 'ANALYSIS_COMPLETED'::character varying, 'ANALYSIS_FAILED'::character varying, 'REVIEW_CREATED'::character varying, 'REVIEW_APPROVED'::character varying, 'REVIEW_REJECTED'::character varying, 'RISK_PATTERN_PROMOTED'::character varying, 'RISK_PATTERN_UPDATED'::character varying, 'RISK_PATTERN_ACTIVATED'::character varying, 'GUARDFIT_ACTION_CREATED'::character varying, 'GUARDFIT_ACTION_UPDATED'::character varying, 'GUARDFIT_ACTION_APPROVED'::character varying])::text[]))),
    CONSTRAINT ck_audit_events_action_resource_type CHECK (((((action)::text = ANY ((ARRAY['ANALYSIS_CREATED'::character varying, 'ANALYSIS_RETRIED'::character varying, 'ANALYSIS_COMPLETED'::character varying, 'ANALYSIS_FAILED'::character varying])::text[])) AND ((resource_type)::text = 'ANALYSIS'::text)) OR (((action)::text = ANY ((ARRAY['REVIEW_CREATED'::character varying, 'REVIEW_APPROVED'::character varying, 'REVIEW_REJECTED'::character varying])::text[])) AND ((resource_type)::text = 'REVIEW'::text)) OR (((action)::text = ANY ((ARRAY['RISK_PATTERN_PROMOTED'::character varying, 'RISK_PATTERN_UPDATED'::character varying, 'RISK_PATTERN_ACTIVATED'::character varying])::text[])) AND ((resource_type)::text = 'RISK_PATTERN'::text)) OR (((action)::text = ANY ((ARRAY['GUARDFIT_ACTION_CREATED'::character varying, 'GUARDFIT_ACTION_UPDATED'::character varying, 'GUARDFIT_ACTION_APPROVED'::character varying])::text[])) AND ((resource_type)::text = 'GUARDFIT_ACTION'::text)))),
    CONSTRAINT ck_audit_events_resource_type CHECK (((resource_type)::text = ANY ((ARRAY['ANALYSIS'::character varying, 'REVIEW'::character varying, 'RISK_PATTERN'::character varying, 'GUARDFIT_ACTION'::character varying])::text[])))
);


--
-- Name: audit_events_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_events ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_corpus_artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demo_corpus_artifacts (
    logical_id character varying(120) NOT NULL,
    artifact_path character varying(500) NOT NULL,
    artifact_sha256 character(64) NOT NULL,
    artifact_version character varying(50) NOT NULL,
    license character varying(50) NOT NULL,
    synthetic boolean NOT NULL,
    demo_only boolean NOT NULL,
    evidence_document_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_demo_corpus_artifact_license CHECK ((btrim((license)::text) <> ''::text)),
    CONSTRAINT ck_demo_corpus_artifact_sha256 CHECK ((artifact_sha256 ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_demo_corpus_artifact_synthetic CHECK (((synthetic = true) AND (demo_only = true))),
    CONSTRAINT ck_demo_corpus_artifact_version CHECK ((btrim((artifact_version)::text) <> ''::text))
);


--
-- Name: TABLE demo_corpus_artifacts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.demo_corpus_artifacts IS 'Auditable logical-id-to-file/database mapping for the 100% synthetic, demo-only canonical corpus; it confers no legal or regulatory authority.';


--
-- Name: COLUMN demo_corpus_artifacts.artifact_sha256; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.demo_corpus_artifacts.artifact_sha256 IS 'Lowercase SHA-256 of the canonical PDF bytes recorded in data/demo-corpus/manifest.v1.json.';


--
-- Name: COLUMN demo_corpus_artifacts.evidence_document_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.demo_corpus_artifacts.evidence_document_id IS 'Active retrieval evidence row, or NULL when the artifact is product input rather than retrieval evidence.';


--
-- Name: demo_corpus_evidence_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demo_corpus_evidence_mappings (
    product_logical_id character varying(120) NOT NULL,
    evidence_logical_id character varying(120) NOT NULL,
    evidence_document_id bigint NOT NULL,
    selection_order smallint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_demo_corpus_mapping_distinct_artifacts CHECK (((product_logical_id)::text <> (evidence_logical_id)::text)),
    CONSTRAINT ck_demo_corpus_mapping_selection_order CHECK ((selection_order > 0))
);


--
-- Name: TABLE demo_corpus_evidence_mappings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.demo_corpus_evidence_mappings IS 'Explicit demo-only product logical-id to selected evidence logical-id and evidence_documents database-id mapping.';


--
-- Name: evidence_document_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_document_chunks (
    id bigint NOT NULL,
    evidence_document_id bigint NOT NULL,
    source_hash character varying(64) NOT NULL,
    chunk_ordinal integer NOT NULL,
    chunking_version character varying(100) NOT NULL,
    chunk_hash character varying(64) NOT NULL,
    chunk_text text NOT NULL,
    embedding_model character varying(255) NOT NULL,
    embedding public.vector(1024) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_evidence_document_chunks_chunk_hash CHECK (((chunk_hash)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_evidence_document_chunks_chunking_version CHECK ((btrim((chunking_version)::text) <> ''::text)),
    CONSTRAINT ck_evidence_document_chunks_embedding_model CHECK ((btrim((embedding_model)::text) <> ''::text)),
    CONSTRAINT ck_evidence_document_chunks_embedding_non_zero CHECK ((public.vector_norm(embedding) > (0)::double precision)),
    CONSTRAINT ck_evidence_document_chunks_ordinal CHECK ((chunk_ordinal >= 0)),
    CONSTRAINT ck_evidence_document_chunks_source_hash CHECK (((source_hash)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_evidence_document_chunks_text CHECK ((btrim(chunk_text) <> ''::text))
);


--
-- Name: TABLE evidence_document_chunks; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.evidence_document_chunks IS 'Deterministically versioned evidence chunks and their Ollama embeddings for pgvector retrieval.';


--
-- Name: COLUMN evidence_document_chunks.source_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.evidence_document_chunks.source_hash IS 'Lowercase SHA-256 hex of the complete source text used for this indexing pass.';


--
-- Name: COLUMN evidence_document_chunks.chunk_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.evidence_document_chunks.chunk_hash IS 'Lowercase SHA-256 hex of chunk_text.';


--
-- Name: CONSTRAINT ck_evidence_document_chunks_embedding_non_zero ON evidence_document_chunks; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON CONSTRAINT ck_evidence_document_chunks_embedding_non_zero ON public.evidence_document_chunks IS 'Cosine retrieval requires embeddings with non-zero Euclidean norm.';


--
-- Name: evidence_document_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidence_document_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_document_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidence_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_documents (
    id bigint NOT NULL,
    source_type character varying(30) NOT NULL,
    title character varying(255) NOT NULL,
    version character varying(50),
    content text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_evidence_documents_source_type CHECK (((source_type)::text = ANY ((ARRAY['INTERNAL_POLICY'::character varying, 'REGULATION'::character varying, 'PRODUCT_POLICY'::character varying])::text[])))
);


--
-- Name: TABLE evidence_documents; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.evidence_documents IS '공식 승인 근거 라이브러리. 담당자는 선택만 한다.';


--
-- Name: evidence_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidence_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidence_references; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_references (
    id bigint NOT NULL,
    finding_id bigint NOT NULL,
    evidence_document_id bigint NOT NULL,
    excerpt text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: evidence_references_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidence_references ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidence_references_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finding_affected_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finding_affected_personas (
    finding_id bigint NOT NULL,
    persona_template_id bigint NOT NULL
);


--
-- Name: findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.findings (
    id bigint NOT NULL,
    analysis_id bigint NOT NULL,
    statement text NOT NULL,
    severity character varying(10) NOT NULL,
    recommendation text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_findings_severity CHECK (((severity)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[])))
);


--
-- Name: TABLE findings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.findings IS 'HIGH Finding은 evidence_reference를 최소 1개 가져야 한다(앱 검증).';


--
-- Name: findings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.findings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.findings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ground_truth_facts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ground_truth_facts (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    label character varying(255) NOT NULL,
    value text NOT NULL,
    importance character varying(10) NOT NULL,
    verification_status character varying(20) NOT NULL,
    extraction_source character varying(30) NOT NULL,
    source_text_sha256 character varying(64) NOT NULL,
    created_by bigint NOT NULL,
    decided_by bigint,
    decided_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_ground_truth_facts_decision CHECK (((((verification_status)::text = 'CANDIDATE'::text) AND (decided_by IS NULL) AND (decided_at IS NULL)) OR (((verification_status)::text = ANY ((ARRAY['VERIFIED'::character varying, 'REJECTED'::character varying])::text[])) AND (decided_by IS NOT NULL) AND (decided_at IS NOT NULL)))),
    CONSTRAINT ck_ground_truth_facts_extraction_source CHECK (((extraction_source)::text = 'CONFIRMED_DOCUMENT'::text)),
    CONSTRAINT ck_ground_truth_facts_importance CHECK (((importance)::text = 'HIGH'::text)),
    CONSTRAINT ck_ground_truth_facts_source_text_sha256 CHECK (((source_text_sha256)::text ~ '^[0-9a-f]{64}$'::text)),
    CONSTRAINT ck_ground_truth_facts_verification_status CHECK (((verification_status)::text = ANY ((ARRAY['CANDIDATE'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: TABLE ground_truth_facts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ground_truth_facts IS '담당자가 확인한 product_document 원문 전체의 현재 공식 사실 스냅샷. 문서당 한 건만 유지한다.';


--
-- Name: COLUMN ground_truth_facts.value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ground_truth_facts.value IS 'AI 요약이나 fixture가 아닌 product_documents.extracted_text의 사람 확인 당시 원문.';


--
-- Name: COLUMN ground_truth_facts.source_text_sha256; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ground_truth_facts.source_text_sha256 IS 'value 원문의 SHA-256 lowercase hex. 확인 텍스트 변경 여부를 판별한다.';


--
-- Name: ground_truth_facts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ground_truth_facts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ground_truth_facts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guardfit_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guardfit_actions (
    id bigint NOT NULL,
    risk_pattern_id bigint NOT NULL,
    action_type character varying(20) NOT NULL,
    label character varying(255) NOT NULL,
    placement character varying(255) NOT NULL,
    required boolean DEFAULT false NOT NULL,
    preview text,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    updated_by bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_guardfit_actions_status CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'APPROVED'::character varying])::text[]))),
    CONSTRAINT ck_guardfit_actions_type CHECK (((action_type)::text = ANY ((ARRAY['LABEL'::character varying, 'WARNING'::character varying, 'QUESTION'::character varying, 'COMPARISON'::character varying])::text[])))
);


--
-- Name: TABLE guardfit_actions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.guardfit_actions IS 'WARNING_LABEL/DISCARDED는 사용하지 않는다(확정).';


--
-- Name: guardfit_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guardfit_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardfit_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idempotency_claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idempotency_claims (
    id bigint NOT NULL,
    actor_id bigint NOT NULL,
    operation character varying(32) NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    analysis_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_idempotency_claims_operation CHECK (((operation)::text = 'ANALYSIS_CREATE'::text)),
    CONSTRAINT ck_idempotency_claims_request_fingerprint CHECK (((request_fingerprint)::text ~ '^[0-9a-f]{64}$'::text))
);


--
-- Name: TABLE idempotency_claims; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.idempotency_claims IS '사용자별 분석 생성 멱등성 선점. analysis_id가 채워지면 승자 요청이 완료된 상태다.';


--
-- Name: COLUMN idempotency_claims.request_fingerprint; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.idempotency_claims.request_fingerprint IS '정규화된 분석 생성 요청의 lowercase SHA-256 hex.';


--
-- Name: idempotency_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.idempotency_claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.idempotency_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona_templates (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    criteria jsonb,
    risk_focus jsonb,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_persona_templates_code CHECK (((code)::text = ANY ((ARRAY['FINANCIAL_BEGINNER'::character varying, 'SENIOR'::character varying, 'LOSS_EXPERIENCED'::character varying, 'SHORT_TERM_LIQUIDITY'::character varying, 'SELF_EMPLOYED'::character varying])::text[])))
);


--
-- Name: TABLE persona_templates; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.persona_templates IS '고정 AI 소비자 Persona 5종(lookup). 시스템 사용자가 아니다.';


--
-- Name: persona_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_documents (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    media_type character varying(150) NOT NULL,
    file_size bigint,
    checksum character varying(64),
    storage_key character varying(500) NOT NULL,
    extract_status character varying(20) DEFAULT 'UPLOADED'::character varying NOT NULL,
    extracted_text text,
    confirmed boolean DEFAULT false NOT NULL,
    confirmed_by bigint,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_product_documents_extract_status CHECK (((extract_status)::text = ANY ((ARRAY['UPLOADED'::character varying, 'EXTRACTING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: TABLE product_documents; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_documents IS '파일 메타 + 추출 텍스트. 바이너리는 영구 저장하지 않으며 storage_key는 mock:// 포인터다.';


--
-- Name: COLUMN product_documents.checksum; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.product_documents.checksum IS 'SHA-256 hex(64자). 업로드 스트림에서 계산하고 바이너리는 폐기한다.';


--
-- Name: product_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    product_type character varying(20) NOT NULL,
    description character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_products_type CHECK (((product_type)::text = ANY ((ARRAY['INVESTMENT'::character varying, 'LOAN'::character varying, 'SAVINGS'::character varying])::text[])))
);


--
-- Name: TABLE products; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.products IS '분석의 최상위 컨텍스트. status 컬럼 없음(확정).';


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: red_team_packs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.red_team_packs (
    id bigint NOT NULL,
    code character varying(60) NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: red_team_packs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.red_team_packs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.red_team_packs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: red_team_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.red_team_rules (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    pack_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    sort_order integer,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_red_team_rules_code CHECK (((code)::text = ANY ((ARRAY['RETURN_FRAMING'::character varying, 'LOSS_SOFTENING'::character varying, 'COST_OMISSION'::character varying, 'STABILITY_KEYWORD'::character varying, 'FORMAL_CONFIRMATION'::character varying, 'COGNITIVE_ACCESSIBILITY'::character varying])::text[])))
);


--
-- Name: red_team_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.red_team_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.red_team_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_selected_findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_selected_findings (
    review_id bigint NOT NULL,
    finding_id bigint NOT NULL
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    analysis_id bigint NOT NULL,
    reviewer_id bigint,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    comment character varying(1000),
    decided_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    submission_comment character varying(500),
    CONSTRAINT ck_reviews_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: TABLE reviews; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.reviews IS '분석당 1검토(UNIQUE). 결정은 별도 decision이 아니라 status에 통합한다.';


--
-- Name: COLUMN reviews.submission_comment; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.reviews.submission_comment IS '상품 담당자가 검토 요청 시 남긴 선택 의견. 검토자의 결정 사유(comment)와 별도로 보존한다.';


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: risk_patterns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_patterns (
    id bigint NOT NULL,
    finding_id bigint NOT NULL,
    review_id bigint,
    name character varying(255) NOT NULL,
    severity character varying(10) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_risk_patterns_severity CHECK (((severity)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT ck_risk_patterns_status CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: TABLE risk_patterns; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.risk_patterns IS '승인된 Finding만 승격한다. 영향 Persona/근거는 finding으로 역추적한다.';


--
-- Name: risk_patterns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.risk_patterns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risk_patterns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(30) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_users_role CHECK (((role)::text = ANY ((ARRAY['PRODUCT_MANAGER'::character varying, 'COMPLIANCE_REVIEWER'::character varying])::text[])))
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS '실제 사용자(상품 담당자/검토자). AI 소비자 Persona는 persona_templates에 저장한다.';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analyses analyses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analyses
    ADD CONSTRAINT analyses_pkey PRIMARY KEY (id);


--
-- Name: analysis_evidence_documents analysis_evidence_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_evidence_documents
    ADD CONSTRAINT analysis_evidence_documents_pkey PRIMARY KEY (analysis_id, evidence_document_id);


--
-- Name: analysis_ground_truth_fact_snapshots analysis_ground_truth_fact_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_ground_truth_fact_snapshots
    ADD CONSTRAINT analysis_ground_truth_fact_snapshots_pkey PRIMARY KEY (id);


--
-- Name: analysis_personas analysis_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_personas
    ADD CONSTRAINT analysis_personas_pkey PRIMARY KEY (analysis_id, persona_template_id);


--
-- Name: analysis_rag_retrieval_snapshots analysis_rag_retrieval_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT analysis_rag_retrieval_snapshots_pkey PRIMARY KEY (id);


--
-- Name: analysis_rag_runs analysis_rag_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_runs
    ADD CONSTRAINT analysis_rag_runs_pkey PRIMARY KEY (id);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (audit_id);


--
-- Name: demo_corpus_artifacts demo_corpus_artifacts_artifact_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT demo_corpus_artifacts_artifact_path_key UNIQUE (artifact_path);


--
-- Name: demo_corpus_artifacts demo_corpus_artifacts_artifact_sha256_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT demo_corpus_artifacts_artifact_sha256_key UNIQUE (artifact_sha256);


--
-- Name: demo_corpus_artifacts demo_corpus_artifacts_evidence_document_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT demo_corpus_artifacts_evidence_document_id_key UNIQUE (evidence_document_id);


--
-- Name: demo_corpus_artifacts demo_corpus_artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT demo_corpus_artifacts_pkey PRIMARY KEY (logical_id);


--
-- Name: demo_corpus_evidence_mappings demo_corpus_evidence_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_evidence_mappings
    ADD CONSTRAINT demo_corpus_evidence_mappings_pkey PRIMARY KEY (product_logical_id, evidence_logical_id);


--
-- Name: evidence_document_chunks evidence_document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_document_chunks
    ADD CONSTRAINT evidence_document_chunks_pkey PRIMARY KEY (id);


--
-- Name: evidence_documents evidence_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_documents
    ADD CONSTRAINT evidence_documents_pkey PRIMARY KEY (id);


--
-- Name: evidence_references evidence_references_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_references
    ADD CONSTRAINT evidence_references_pkey PRIMARY KEY (id);


--
-- Name: finding_affected_personas finding_affected_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finding_affected_personas
    ADD CONSTRAINT finding_affected_personas_pkey PRIMARY KEY (finding_id, persona_template_id);


--
-- Name: findings findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_pkey PRIMARY KEY (id);


--
-- Name: ground_truth_facts ground_truth_facts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_truth_facts
    ADD CONSTRAINT ground_truth_facts_pkey PRIMARY KEY (id);


--
-- Name: guardfit_actions guardfit_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardfit_actions
    ADD CONSTRAINT guardfit_actions_pkey PRIMARY KEY (id);


--
-- Name: idempotency_claims idempotency_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_claims
    ADD CONSTRAINT idempotency_claims_pkey PRIMARY KEY (id);


--
-- Name: persona_templates persona_templates_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_templates
    ADD CONSTRAINT persona_templates_code_key UNIQUE (code);


--
-- Name: persona_templates persona_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_templates
    ADD CONSTRAINT persona_templates_pkey PRIMARY KEY (id);


--
-- Name: product_documents product_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_documents
    ADD CONSTRAINT product_documents_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: red_team_packs red_team_packs_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.red_team_packs
    ADD CONSTRAINT red_team_packs_code_key UNIQUE (code);


--
-- Name: red_team_packs red_team_packs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.red_team_packs
    ADD CONSTRAINT red_team_packs_pkey PRIMARY KEY (id);


--
-- Name: red_team_rules red_team_rules_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.red_team_rules
    ADD CONSTRAINT red_team_rules_code_key UNIQUE (code);


--
-- Name: red_team_rules red_team_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.red_team_rules
    ADD CONSTRAINT red_team_rules_pkey PRIMARY KEY (id);


--
-- Name: review_selected_findings review_selected_findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_selected_findings
    ADD CONSTRAINT review_selected_findings_pkey PRIMARY KEY (review_id, finding_id);


--
-- Name: reviews reviews_analysis_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_analysis_id_key UNIQUE (analysis_id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: risk_patterns risk_patterns_finding_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_patterns
    ADD CONSTRAINT risk_patterns_finding_id_key UNIQUE (finding_id);


--
-- Name: risk_patterns risk_patterns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_patterns
    ADD CONSTRAINT risk_patterns_pkey PRIMARY KEY (id);


--
-- Name: demo_corpus_artifacts uq_demo_corpus_artifact_evidence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT uq_demo_corpus_artifact_evidence UNIQUE (logical_id, evidence_document_id);


--
-- Name: demo_corpus_evidence_mappings uq_demo_corpus_mapping_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_evidence_mappings
    ADD CONSTRAINT uq_demo_corpus_mapping_document UNIQUE (product_logical_id, evidence_document_id);


--
-- Name: demo_corpus_evidence_mappings uq_demo_corpus_mapping_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_evidence_mappings
    ADD CONSTRAINT uq_demo_corpus_mapping_order UNIQUE (product_logical_id, selection_order);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: analysis_ground_truth_fact_snapshots ux_analysis_ground_truth_fact_snapshots_fact; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_ground_truth_fact_snapshots
    ADD CONSTRAINT ux_analysis_ground_truth_fact_snapshots_fact UNIQUE (analysis_id, ground_truth_fact_id);


--
-- Name: analysis_rag_runs ux_analysis_rag_runs_analysis; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_runs
    ADD CONSTRAINT ux_analysis_rag_runs_analysis UNIQUE (analysis_id);


--
-- Name: analysis_rag_retrieval_snapshots ux_analysis_rag_snapshots_chunk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT ux_analysis_rag_snapshots_chunk UNIQUE (rag_run_id, evidence_document_chunk_id);


--
-- Name: analysis_rag_retrieval_snapshots ux_analysis_rag_snapshots_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT ux_analysis_rag_snapshots_rank UNIQUE (rag_run_id, rank);


--
-- Name: evidence_document_chunks ux_evidence_document_chunks_id_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_document_chunks
    ADD CONSTRAINT ux_evidence_document_chunks_id_document UNIQUE (id, evidence_document_id);


--
-- Name: evidence_document_chunks ux_evidence_document_chunks_identity; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_document_chunks
    ADD CONSTRAINT ux_evidence_document_chunks_identity UNIQUE (evidence_document_id, source_hash, chunking_version, embedding_model, chunk_ordinal);


--
-- Name: ground_truth_facts ux_ground_truth_facts_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_truth_facts
    ADD CONSTRAINT ux_ground_truth_facts_document UNIQUE (document_id);


--
-- Name: idempotency_claims ux_idempotency_claims_actor_operation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_claims
    ADD CONSTRAINT ux_idempotency_claims_actor_operation_key UNIQUE (actor_id, operation, idempotency_key);


--
-- Name: idx_analyses_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analyses_document ON public.analyses USING btree (product_document_id);


--
-- Name: idx_analyses_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analyses_status ON public.analyses USING btree (status);


--
-- Name: idx_analysis_ground_truth_fact_snapshots_analysis; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_ground_truth_fact_snapshots_analysis ON public.analysis_ground_truth_fact_snapshots USING btree (analysis_id);


--
-- Name: idx_analysis_rag_snapshots_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_rag_snapshots_document ON public.analysis_rag_retrieval_snapshots USING btree (evidence_document_id);


--
-- Name: idx_analysis_rag_snapshots_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analysis_rag_snapshots_run ON public.analysis_rag_retrieval_snapshots USING btree (rag_run_id);


--
-- Name: idx_audit_events_created_at_audit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_events_created_at_audit_id ON public.audit_events USING btree (created_at DESC, audit_id DESC);


--
-- Name: idx_evidence_document_chunks_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_document_chunks_document ON public.evidence_document_chunks USING btree (evidence_document_id);


--
-- Name: idx_evidence_document_chunks_embedding_cosine; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_document_chunks_embedding_cosine ON public.evidence_document_chunks USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_evidence_document_chunks_source_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_document_chunks_source_hash ON public.evidence_document_chunks USING btree (source_hash);


--
-- Name: idx_evidence_references_finding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_references_finding ON public.evidence_references USING btree (finding_id);


--
-- Name: idx_findings_analysis; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_findings_analysis ON public.findings USING btree (analysis_id);


--
-- Name: idx_guardfit_actions_pattern; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guardfit_actions_pattern ON public.guardfit_actions USING btree (risk_pattern_id);


--
-- Name: idx_product_documents_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_documents_product ON public.product_documents USING btree (product_id);


--
-- Name: idx_products_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_owner ON public.products USING btree (owner_id);


--
-- Name: idx_red_team_rules_pack; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_red_team_rules_pack ON public.red_team_rules USING btree (pack_id);


--
-- Name: idx_reviews_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);


--
-- Name: ux_analyses_document_input_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_analyses_document_input_hash ON public.analyses USING btree (product_document_id, input_hash) WHERE ((status)::text <> 'FAILED'::text);


--
-- Name: analysis_rag_retrieval_snapshots trg_analysis_rag_retrieval_snapshots_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_analysis_rag_retrieval_snapshots_immutable BEFORE DELETE OR UPDATE ON public.analysis_rag_retrieval_snapshots FOR EACH ROW EXECUTE FUNCTION public.reject_analysis_rag_snapshot_changes();


--
-- Name: analysis_rag_runs trg_analysis_rag_runs_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_analysis_rag_runs_immutable BEFORE DELETE OR UPDATE ON public.analysis_rag_runs FOR EACH ROW EXECUTE FUNCTION public.reject_analysis_rag_run_changes();


--
-- Name: audit_events trg_audit_events_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_audit_events_append_only BEFORE DELETE OR UPDATE OR TRUNCATE ON public.audit_events FOR EACH STATEMENT EXECUTE FUNCTION public.reject_audit_event_mutation();


--
-- Name: analyses analyses_product_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analyses
    ADD CONSTRAINT analyses_product_document_id_fkey FOREIGN KEY (product_document_id) REFERENCES public.product_documents(id);


--
-- Name: analyses analyses_red_team_pack_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analyses
    ADD CONSTRAINT analyses_red_team_pack_id_fkey FOREIGN KEY (red_team_pack_id) REFERENCES public.red_team_packs(id);


--
-- Name: analysis_evidence_documents analysis_evidence_documents_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_evidence_documents
    ADD CONSTRAINT analysis_evidence_documents_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: analysis_evidence_documents analysis_evidence_documents_evidence_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_evidence_documents
    ADD CONSTRAINT analysis_evidence_documents_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES public.evidence_documents(id);


--
-- Name: analysis_ground_truth_fact_snapshots analysis_ground_truth_fact_snapshots_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_ground_truth_fact_snapshots
    ADD CONSTRAINT analysis_ground_truth_fact_snapshots_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: analysis_ground_truth_fact_snapshots analysis_ground_truth_fact_snapshots_ground_truth_fact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_ground_truth_fact_snapshots
    ADD CONSTRAINT analysis_ground_truth_fact_snapshots_ground_truth_fact_id_fkey FOREIGN KEY (ground_truth_fact_id) REFERENCES public.ground_truth_facts(id);


--
-- Name: analysis_personas analysis_personas_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_personas
    ADD CONSTRAINT analysis_personas_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: analysis_personas analysis_personas_persona_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_personas
    ADD CONSTRAINT analysis_personas_persona_template_id_fkey FOREIGN KEY (persona_template_id) REFERENCES public.persona_templates(id);


--
-- Name: analysis_rag_retrieval_snapshots analysis_rag_retrieval_snapshots_evidence_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT analysis_rag_retrieval_snapshots_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES public.evidence_documents(id);


--
-- Name: analysis_rag_retrieval_snapshots analysis_rag_retrieval_snapshots_rag_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT analysis_rag_retrieval_snapshots_rag_run_id_fkey FOREIGN KEY (rag_run_id) REFERENCES public.analysis_rag_runs(id) ON DELETE CASCADE;


--
-- Name: analysis_rag_runs analysis_rag_runs_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_runs
    ADD CONSTRAINT analysis_rag_runs_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: demo_corpus_artifacts demo_corpus_artifacts_evidence_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_artifacts
    ADD CONSTRAINT demo_corpus_artifacts_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES public.evidence_documents(id);


--
-- Name: demo_corpus_evidence_mappings demo_corpus_evidence_mappings_product_logical_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_evidence_mappings
    ADD CONSTRAINT demo_corpus_evidence_mappings_product_logical_id_fkey FOREIGN KEY (product_logical_id) REFERENCES public.demo_corpus_artifacts(logical_id);


--
-- Name: evidence_document_chunks evidence_document_chunks_evidence_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_document_chunks
    ADD CONSTRAINT evidence_document_chunks_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES public.evidence_documents(id) ON DELETE CASCADE;


--
-- Name: evidence_references evidence_references_evidence_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_references
    ADD CONSTRAINT evidence_references_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES public.evidence_documents(id);


--
-- Name: evidence_references evidence_references_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_references
    ADD CONSTRAINT evidence_references_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id) ON DELETE CASCADE;


--
-- Name: finding_affected_personas finding_affected_personas_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finding_affected_personas
    ADD CONSTRAINT finding_affected_personas_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id) ON DELETE CASCADE;


--
-- Name: finding_affected_personas finding_affected_personas_persona_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finding_affected_personas
    ADD CONSTRAINT finding_affected_personas_persona_template_id_fkey FOREIGN KEY (persona_template_id) REFERENCES public.persona_templates(id);


--
-- Name: findings findings_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: analysis_rag_retrieval_snapshots fk_analysis_rag_snapshots_chunk_document; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_rag_retrieval_snapshots
    ADD CONSTRAINT fk_analysis_rag_snapshots_chunk_document FOREIGN KEY (evidence_document_chunk_id, evidence_document_id) REFERENCES public.evidence_document_chunks(id, evidence_document_id);


--
-- Name: demo_corpus_evidence_mappings fk_demo_corpus_mapping_evidence; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_corpus_evidence_mappings
    ADD CONSTRAINT fk_demo_corpus_mapping_evidence FOREIGN KEY (evidence_logical_id, evidence_document_id) REFERENCES public.demo_corpus_artifacts(logical_id, evidence_document_id);


--
-- Name: ground_truth_facts ground_truth_facts_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_truth_facts
    ADD CONSTRAINT ground_truth_facts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: ground_truth_facts ground_truth_facts_decided_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_truth_facts
    ADD CONSTRAINT ground_truth_facts_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.users(id);


--
-- Name: ground_truth_facts ground_truth_facts_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_truth_facts
    ADD CONSTRAINT ground_truth_facts_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.product_documents(id) ON DELETE CASCADE;


--
-- Name: guardfit_actions guardfit_actions_risk_pattern_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardfit_actions
    ADD CONSTRAINT guardfit_actions_risk_pattern_id_fkey FOREIGN KEY (risk_pattern_id) REFERENCES public.risk_patterns(id) ON DELETE CASCADE;


--
-- Name: guardfit_actions guardfit_actions_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guardfit_actions
    ADD CONSTRAINT guardfit_actions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: idempotency_claims idempotency_claims_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_claims
    ADD CONSTRAINT idempotency_claims_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: idempotency_claims idempotency_claims_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_claims
    ADD CONSTRAINT idempotency_claims_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id);


--
-- Name: product_documents product_documents_confirmed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_documents
    ADD CONSTRAINT product_documents_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.users(id);


--
-- Name: product_documents product_documents_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_documents
    ADD CONSTRAINT product_documents_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: products products_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: red_team_rules red_team_rules_pack_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.red_team_rules
    ADD CONSTRAINT red_team_rules_pack_id_fkey FOREIGN KEY (pack_id) REFERENCES public.red_team_packs(id) ON DELETE CASCADE;


--
-- Name: review_selected_findings review_selected_findings_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_selected_findings
    ADD CONSTRAINT review_selected_findings_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id) ON DELETE CASCADE;


--
-- Name: review_selected_findings review_selected_findings_review_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_selected_findings
    ADD CONSTRAINT review_selected_findings_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id) ON DELETE CASCADE;


--
-- Name: reviews reviews_analysis_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id) ON DELETE CASCADE;


--
-- Name: reviews reviews_reviewer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id);


--
-- Name: risk_patterns risk_patterns_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_patterns
    ADD CONSTRAINT risk_patterns_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id);


--
-- Name: risk_patterns risk_patterns_review_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_patterns
    ADD CONSTRAINT risk_patterns_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict tsodcdmk6SyUUqd1WW45XMggaPNwPMzsxYBXi9i8znBwtCw4PJcAYsJV4nAAEaD
